import json, os, shutil
S = os.path.dirname(os.path.abspath(__file__))
P = json.load(open(os.path.join(S, 'parts/panels.json')))
H = {
'admin': dict(role='Hospital Admin', greet='Good morning, Kavita', sub='Setup, users and day-to-day operations for Main Branch',
  quick=[['Add user', 'Users'], ['Register department', 'Departments'], ['Bed board', 'Beds']],
  kpis=[['Occupancy', '86%', '103 of 120 beds', 'Beds'], ['OPD today', '412', '64 waiting', 'FrontOffice'], ['My requests pending', '3', 'with Super Admin', 'Approvals'], ['Users', '74 / 100', 'licences used', 'Users'], ['Low stock items', '17', 'central store', 'Inventory']],
  q=['My requests waiting for approval', 'Changes you made that a checker must approve', 'Approvals'], head=['Request', 'Raised', 'Waiting with', 'Status'],
  rows=[['New user: Rahul Mehta (Billing Manager)', '08 Oct', 'Super Admin', '~ba:Pending'], ['Department: Nephrology', '07 Oct', 'Super Admin', '~ba:Pending'], ['Tariff: ECG ₹280 to ₹300', '05 Oct', '-', '~bg:Approved'], ['Ward: Day care beds (Phase 2)', '02 Oct', '-', '~bn:Draft']],
  alerts=[['Licence limit near', '116 of 120 beds licensed', 'Limit', 'ba'], ['User locked', 'lalit.g after 5 failed logins', 'Unlock', 'br'], ['Template change', 'Lab report header updated', 'Info', 'bb']]),
'medsupt': dict(role='Medical Superintendent', greet='Good morning, Dr. Kulkarni', sub='Clinical operations across wards',
  quick=[['Bed board', 'Beds'], ['Discharges', 'Discharge'], ['Quality', 'Quality']],
  kpis=[['Occupancy', '86%', 'ICU 100%', 'Beds'], ['Discharges due', '6', '2 delayed', 'Discharge'], ['Critical results', '2', 'unacknowledged', 'Approvals'], ['Incidents open', '4', '1 new today', 'Quality'], ['Record deficiencies', '58', '31 files open', 'Records']],
  q=['Needs your decision', 'Clinical approvals and escalations', 'Approvals'], head=['Item', 'Patient', 'Raised by', 'Since', 'Status'],
  rows=[['Discharge with dues ₹18,400', 'A. Joshi', 'Billing Manager', '2 h', '~ba:Approve'], ['Record release to insurer', 'S. Patil', 'MRD Officer', '1 day', '~ba:Approve'], ['ICU bed escalation', 'Ravi Kumar', 'Dr. Meera Iyer', '20 min', '~br:Urgent'], ['Death certificate (MCCD) review', 'H. Singh', 'Dr. R. Menon', '3 days', '~bn:Review']],
  alerts=[['ICU full', 'No ICU bed free; 1 planned transfer', 'Beds', 'br'], ['Discharge TAT missed', 'September 3.4 h vs 3 h target', 'NABH', 'ba'], ['Fall in Ward 2', 'Investigation open', 'Incident', 'ba']]),
'doctor': dict(role='Consultant · Cardiology', greet='Good morning, Dr. Meera Iyer', sub='Your OPD, in-patients and pending sign-offs',
  quick=[['Start OPD', 'Consult'], ['Ward rounds', 'IpdRounds'], ['Sign summaries', 'Discharge']],
  kpis=[['OPD today', '18', '7 seen, 3 waiting', 'Consult'], ['My in-patients', '6', '1 in ICU', 'IpdRounds'], ['Results to review', '9', '1 critical', 'Lab'], ['Summaries to sign', '2', 'discharges today', 'Discharge'], ['Follow-ups due', '14', 'this week', 'PatientProfile']],
  q=['My OPD queue', 'Room 12 · 10:00 to 13:00', 'Consult'], head=['Token', 'Patient', 'Visit', 'Waited', 'Status'],
  rows=[['#T-07', 'Ravi Kumar', 'Follow-up', '14 min', '~bo:In consult'], ['#T-08', 'Divya R.', 'New', '9 min', '~bg:Vitals done'], ['#T-09', 'Harish V.', 'New', '4 min', '~bg:Checked in'], ['#T-10', 'Seema D.', 'Follow-up', '-', '~bb:Booked'], ['#T-11', 'Rahul P.', 'Tele-consult', '-', '~bb:Booked 11:40']],
  alerts=[['Critical: Troponin I high', 'N. Iyer · W2-203-B · 10:31', 'Critical', 'br'], ['Admission request accepted', 'Ravi Kumar → W2-204-B', 'IPD', 'bb'], ['Echo report signed', 'Ravi Kumar', 'Result', 'bg']]),
'nurse': dict(role='Staff Nurse · Ward 2', greet='Good morning, Anjali', sub='Morning shift 07:00 to 14:00 · 5 patients assigned',
  quick=[['Nursing station', 'Nursing'], ['Give 10:00 doses', 'Nursing'], ['Report incident', 'Quality']],
  kpis=[['My patients', '5', 'of 10 in ward', 'Nursing'], ['Meds due', '9', 'next hour', 'Nursing'], ['Vitals due', '5', 'by 12:00', 'Nursing'], ['Indents open', '2', 'pharmacy', 'Nursing'], ['Handover', '13:45', 'to evening shift', 'Nursing']],
  q=['My tasks this hour', 'From doctor orders and care plans', 'Nursing'], head=['Time', 'Bed', 'Patient', 'Task', 'Status'],
  rows=[['10:00', '#W2-204-B', 'Ravi Kumar', 'Enoxaparin 60 mg SC', '~bo:Due'], ['10:00', '#W2-201-A', 'S. Patil', 'Nebulisation', '~bo:Due'], ['10:00', '#W2-204-A', 'F. Ali', 'Vitals and platelet watch', '~br:Late'], ['10:30', '#W2-203-A', 'M. Lal', 'Dressing, diabetic foot', '~bb:Upcoming'], ['11:00', '#W2-205-A', 'K. Nair', 'Discharge teaching', '~bb:Upcoming']],
  alerts=[['Critical result', 'F. Ali platelets 38,000', 'Critical', 'br'], ['Diet changed', 'Ravi Kumar → low-salt cardiac', 'Diet', 'bb'], ['Swap approved', 'Fri 17 Morning', 'Roster', 'bg']]),
'wardincharge': dict(role='Ward In-charge · Ward 2', greet='Good morning, Lata', sub='Ward 2 · 10 of 12 beds · 4 nurses on shift',
  quick=[['Roster', 'Roster'], ['Nursing station', 'Nursing'], ['Indent to store', 'Inventory']],
  kpis=[['Occupied', '10 / 12', '1 discharge today', 'Beds'], ['Staff on shift', '4', 'minimum 3', 'Roster'], ['Overdue tasks', '3', 'across ward', 'Nursing'], ['Swap requests', '2', 'to approve', 'Approvals'], ['Linen below par', '1', 'bedsheets', 'Facility']],
  q=['Ward overview', 'Patients needing attention', 'Nursing'], head=['Bed', 'Patient', 'Concern', 'Nurse', 'Status'],
  rows=[['#W2-204-A', 'F. Ali', 'Platelets critical', 'Anjali', '~br:Watch'], ['#W2-206-B', 'P. Rao', 'Nil by mouth until 14:00', 'Joseph', '~ba:NBM'], ['#W2-202-A', 'A. Joshi', 'Fall risk, post-op', 'Meera', '~ba:Fall risk'], ['#W2-205-A', 'K. Nair', 'Discharge 14:00', 'Anjali', '~bg:Discharge']],
  alerts=[['Night cover short', 'Sat 18 Oct below 2', 'Roster', 'br'], ['Incident open', 'Fall INC-0192', 'Quality', 'ba'], ['Indent partly issued', 'SI-1399', 'Store', 'bb']]),
'frontoffice': dict(role='Front Office Executive', greet='Good morning, Anita', sub='Registration counter 1 · Main Branch',
  quick=[['Register patient', 'Patients'], ['Book appointment', 'Opd'], ['Admit', 'Admission']],
  kpis=[['Registered today', '86', '22 new', 'Patients'], ['Appointments', '412', '64 waiting', 'Opd'], ['Tokens waiting', '6', 'registration', 'FrontOffice'], ['Beds free', '9', '3 cleaning', 'Beds'], ['Enquiries', '31', '4 to follow up', 'FrontOffice']],
  q=['Arrivals in the next hour', 'Booked patients not yet checked in', 'Opd'], head=['Time', 'Patient', 'Doctor', 'Type', 'Status'],
  rows=[['11:20', 'Seema D.', 'Dr. Meera Iyer', 'Follow-up', '~bb:Booked'], ['11:30', 'Gopal R.', 'Dr. P. Joshi', 'New', '~bb:Booked'], ['11:40', 'Rahul P.', 'Dr. Meera Iyer', 'Tele-consult', '~bg:Paid online'], ['11:40', 'Kiara S.', 'Dr. A. Thomas', 'Vaccination', '~bb:Booked']],
  alerts=[['Possible duplicate', 'Ravi Kumaar vs Ravi Kumar', 'Check', 'ba'], ['Planned admission 15:00', 'Bed W2-203-B reserved', 'IPD', 'bb'], ['Doctor late', 'Dr. Joshi OPD starts 10:30', 'Info', 'bn']]),
'cashier': dict(role='Cashier · Counter 1', greet='Good morning, Neha', sub='Shift opened 08:00 · ₹1,12,480 collected',
  quick=[['New bill', 'Billing'], ['Collect deposit', 'Billing'], ['Close shift', 'Billing']],
  kpis=[['Collected', '₹1.12 L', 'this shift', 'Billing'], ['Bills', '64', 'this shift', 'Billing'], ['Cash in drawer', '₹22,650', 'counted at close', 'Billing'], ['Waiting', '9', 'token B-119 next', 'Billing'], ['My pending approvals', '1', 'discount 15%', 'Billing']],
  q=['Patients waiting to pay', 'Unbilled charges by patient', 'Billing'], head=['Token', 'Patient', 'Charges', 'Amount', 'Status'],
  rows=[['#B-119', 'Ravi Kumar', 'Lab ×2, ECG, Echo', '₹3,545', '~bo:Next'], ['#B-120', 'Divya R.', 'Health check-up', '₹6,500', '~bb:Waiting'], ['#B-121', 'Sana Sheikh', 'Consultation', '₹2,040', '~ba:Discount pending'], ['#B-122', 'Arif Khan', 'MRI knee', '₹6,800', '~bb:Waiting']],
  alerts=[['Discount sent for approval', 'OP/26-27/000155 · 15%', 'Pending', 'ba'], ['UPI device offline', 'Counter 1 · use QR on screen', 'Device', 'br'], ['Refund paid', 'RF-0090 · ₹8,400', 'Done', 'bg']]),
'billingmgr': dict(role='Billing Manager', greet='Good morning, Rahul', sub='Billing, discounts, refunds and IPD final bills',
  quick=[['Approvals', 'Approvals'], ['Final bills', 'Discharge'], ['Collection report', 'Reports']],
  kpis=[['Collection today', '₹4.82 L', 'all counters', 'Reports'], ['Discounts to approve', '2', '₹2,760', 'Approvals'], ['Refunds pending', '1', '₹650', 'Billing'], ['Final bills due', '6', 'discharges today', 'Discharge'], ['Credit outstanding', '₹6.8 L', 'corporate', 'Billing']],
  q=['Approval queue', 'Discounts, refunds and cancellations', 'Approvals'], head=['Request', 'Bill', 'Amount', 'Maker', 'Status'],
  rows=[['Discount 15%', '#OP/26-27/000155', '₹360', 'Neha', '~ba:L1 you'], ['Refund, test not done', '#OP/26-27/000140', '₹650', 'Neha', '~ba:L1 you'], ['Discharge with dues', '#IP/26-27/000836', '₹18,400', 'Billing desk', '~bb:With Med. Supt.']],
  alerts=[['Low deposit', 'K. Nair balance - ₹12,300', 'IPD', 'br'], ['Duplicate prints', '7 receipts reprinted today', 'Audit', 'ba'], ['Card settlement short', '₹424 fee on 8 Oct', 'Bank', 'bn']]),
'lab': dict(role='Pathologist', greet='Good morning, Dr. Rao', sub='Laboratory · 188 reports released today',
  quick=[['Validate results', 'Lab'], ['Collection worklist', 'Lab'], ['Indent reagents', 'Inventory']],
  kpis=[['To collect', '14', '3 urgent', 'Lab'], ['In process', '22', 'result entry', 'Lab'], ['To validate', '9', '1 critical', 'Lab'], ['Home collections', '11', '4 done', 'Lab'], ['TAT met', '94%', 'routine, today', 'Lab']],
  q=['Awaiting your validation', 'Results entered by technicians', 'Lab'], head=['Sample', 'Patient', 'Test', 'Flags', 'Waiting'],
  rows=[['#LB-26-018842', 'F. Ali', 'CBC', '~br:Critical', '22 min'], ['#LB-26-018851', 'Ravi Kumar', 'Lipid profile', '~ba:High', '15 min'], ['#LB-26-018861', 'K. Nair', 'ABG', '~bo:STAT', '4 min'], ['#LB-26-018874', 'S. Patil', 'Blood culture prelim', '~bb:Micro', '1 h']],
  alerts=[['Critical not acknowledged', 'F. Ali platelets', 'Call', 'br'], ['QC out of range', 'Analyser 2, glucose level 2', 'QC', 'ba'], ['Reagent low', 'HbA1c kit, 2 days left', 'Stock', 'ba']]),
'radiology': dict(role='Radiologist', greet='Good morning, Dr. Singh', sub='Radiology · X-ray, USG, CT, MRI',
  quick=[['Report next', 'Radiology'], ['Schedule', 'Radiology'], ['Equipment ticket', 'Facility']],
  kpis=[['To report', '8', '2 urgent', 'Radiology'], ['Scheduled', '21', 'today', 'Radiology'], ['In progress', '3', 'rooms busy', 'Radiology'], ['Signed', '46', 'today', 'Radiology'], ['Form F pending', '0', 'PCPNDT', 'Radiology']],
  q=['Reporting worklist', 'Oldest first', 'Radiology'], head=['Study', 'Patient', 'Modality', 'Priority', 'Status'],
  rows=[['USG obstetric', 'Priya Shinde', 'USG', '~bn:Routine', '~bo:Reporting'], ['CT brain plain', 'Mohan Lal', 'CT', '~br:Urgent', '~ba:To report'], ['X-ray chest PA', 'S. Patil', 'X-ray', '~bn:Routine', '~ba:To report'], ['MRI L-S spine', 'Usha K.', 'MRI', '~bn:Routine', '~ba:To report']],
  alerts=[['CT contrast check', 'Gopal R. needs creatinine', 'Prep', 'ba'], ['USG AMC renewal', '30 Nov', 'Contract', 'bo'], ['Resident draft ready', 'USG abdomen, Arif Khan', 'Draft', 'bb']]),
'pharmacy': dict(role='Pharmacist', greet='Good morning, Suresh', sub='OPD Pharmacy · 12 prescriptions waiting',
  quick=[['Dispense next', 'Pharmacy'], ['Ward indents', 'Pharmacy'], ['Stock alerts', 'Inventory']],
  kpis=[['Rx waiting', '12', 'P-087 picking', 'Pharmacy'], ['Ward indents', '7', '2 urgent', 'Pharmacy'], ['Sales today', '₹1.39 L', '184 bills', 'Pharmacy'], ['Below reorder', '23', 'items', 'Pharmacy'], ['Expiring 30 days', '9', 'batches', 'Pharmacy']],
  q=['Prescription queue', 'From OPD consultations', 'Pharmacy'], head=['Token', 'Patient', 'Doctor', 'Items', 'Status'],
  rows=[['#P-087', 'Ravi Kumar', 'Dr. Meera Iyer', '4', '~bo:Picking'], ['#P-088', 'Divya R.', 'Dr. R. Menon', '2', '~bb:Waiting'], ['#P-089', 'Baby Ishan', 'Dr. A. Thomas', '3', '~bb:Waiting'], ['#P-090', 'Neeta P.', 'Dr. P. Joshi', '5', '~bb:Waiting']],
  alerts=[['Out of stock', 'Sorbitrate 5 mg · substitute available', 'Stock', 'br'], ['GRN price variance', 'GRN-000318 needs approval', 'Purchase', 'ba'], ['H1 register', '3 entries today', 'Register', 'bb']]),
'store': dict(role='Store Keeper', greet='Good morning, Vikram', sub='Central Store · ₹38.6 L stock',
  quick=[['Issue indents', 'Inventory'], ['New PO', 'Inventory'], ['Receive goods', 'Inventory']],
  kpis=[['Indents to issue', '11', 'oldest 2 days', 'Inventory'], ['Below reorder', '17', '6 on order', 'Inventory'], ['POs open', '9', '2 awaiting approval', 'Inventory'], ['GRN today', '2', 'posted', 'Inventory'], ['Transfers in transit', '1', 'to ICU', 'Inventory']],
  q=['Indents to issue', 'Department requests', 'Inventory'], head=['Indent', 'Department', 'Items', 'Raised', 'Status'],
  rows=[['#SI-1402', 'Ward 2', 'Gloves, syringes, IV sets', '09:10', '~bo:To issue'], ['#SI-1401', 'ICU', 'ECG electrodes, suction catheters', '08:40', '~bo:To issue'], ['#SI-1399', 'OPD', 'Printer paper, wristbands', 'Yesterday', '~bb:Partly issued']],
  alerts=[['Out of stock', 'Urine bag 2 L', 'Stock', 'br'], ['PO approval', 'PO-000412 with Super Admin', 'PO', 'ba'], ['Stock audit due', 'Quarterly count, 15 Oct', 'Audit', 'bn']]),
'hr': dict(role='HR Manager', greet='Good morning, Shalini', sub='412 employees · 361 present today',
  quick=[['Approve leave', 'Hr'], ['Add employee', 'Hr'], ['Payroll status', 'Payroll']],
  kpis=[['Present', '361', '87.6%', 'Hr'], ['Leave to approve', '4', 'requests', 'Hr'], ['Credentials expiring', '6', 'in 60 days', 'Hr'], ['Open positions', '8', '89 candidates', 'Hr'], ['Payroll', 'L1 done', 'with Finance', 'Payroll']],
  q=['Leave requests', 'Waiting for HR or managers', 'Hr'], head=['Employee', 'Type', 'Dates', 'Balance', 'Status'],
  rows=[['Kavya N.', 'Earned leave', '14 to 17 Oct', '9 days', '~ba:Pending'], ['Joseph K.', 'Casual leave', '20 Oct', '3 days', '~ba:Pending'], ['Meera Pillai', 'Sick leave', '9 Oct', '5 days', '~ba:Pending'], ['Ramesh Iyer', 'Comp-off', '13 Oct', '1 day', '~ba:Pending']],
  alerts=[['Registration expiring', 'Rose Thomas in 12 days', 'Credential', 'br'], ['9 absent, not informed', 'Nursing 6, front office 2', 'Attendance', 'ba'], ['Offer accepted', 'Dr. Sahil K. joins 15 Oct', 'Hiring', 'bg']]),
'payroll': dict(role='Payroll Officer', greet='Good morning, Kiran', sub='September payroll · waiting for Finance Controller',
  quick=[['Open payroll run', 'Payroll'], ['Import inputs', 'Payroll'], ['Attendance lock', 'Hr']],
  kpis=[['Employees', '412', 'September', 'Payroll'], ['Net pay', '₹1.63 Cr', 'to release', 'Payroll'], ['Warnings', '3', 'net change over 25%', 'Payroll'], ['Attendance', 'Locked', '30 Sep', 'Hr'], ['Statutory due', '15 Oct', 'PF and ESI', 'Payroll']],
  q=['Payroll run status', 'September 2026', 'Payroll'], head=['Step', 'By', 'When', 'Status'],
  rows=[['Calculated', 'Kiran Joshi', '06 Oct', '~bg:Done'], ['Submitted', 'Kiran Joshi', '07 Oct', '~bg:Done'], ['HR approval', 'Shalini Rao', '08 Oct', '~bg:Approved'], ['Finance release', 'Finance Controller', '-', '~ba:Pending'], ['Lock and payslips', 'System', '-', '~bn:Waiting']],
  alerts=[['Net pay change', 'Imran A. +31%, check arrears', 'Check', 'ba'], ['New joiners', '7 need salary structure', 'Setup', 'bb'], ['PF ECR', 'Due 15 Oct', 'Statutory', 'bo']]),
'accounts': dict(role='Accountant', greet='Good morning, Ramesh', sub='October 2026 · period open',
  quick=[['New voucher', 'Finance'], ['Bank reconciliation', 'Finance'], ['GST returns', 'Finance']],
  kpis=[['Revenue MTD', '₹1.43 Cr', 'up 8%', 'Finance'], ['Payables this week', '₹18.6 L', '14 vendors', 'Finance'], ['Receivables 60+ days', '₹9.4 L', 'corporate', 'Finance'], ['Unreconciled', '37', 'bank lines', 'Finance'], ['Approvals', '2', 'journal, payroll', 'Approvals']],
  q=['Today’s work', 'Postings and items to clear', 'Finance'], head=['Item', 'Source', 'Amount', 'Status'],
  rows=[['Day collections posting', 'Billing', '₹4,82,350', '~bg:Auto-posted'], ['Pharmacy COGS', 'Pharmacy', '₹38,420', '~bg:Auto-posted'], ['Journal JV/0418 doctor payouts', 'Manual', '₹2,40,000', '~ba:Approval'], ['Vendor payment run', 'Payables', '₹18,60,000', '~bb:Prepare']],
  alerts=[['Budget overrun', 'Maintenance 109% of budget', 'Budget', 'br'], ['GSTR-3B', 'Review before 20 Oct', 'GST', 'ba'], ['Petty cash', 'OPD replenishment ₹12,500', 'Approve', 'bb']]),
'mrd': dict(role='MRD Officer', greet='Good morning, Sunil', sub='Medical records · 31 files open',
  quick=[['Deficiencies', 'Records'], ['Birth register', 'Records'], ['Release requests', 'Records']],
  kpis=[['Files not closed', '31', 'after discharge', 'Records'], ['Deficiencies', '58', '12 over 7 days', 'Records'], ['To code', '14', 'ICD-10', 'Records'], ['Release requests', '4', '2 need approval', 'Records'], ['CRS reports due', '3', 'births and deaths', 'Records']],
  q=['Deficiencies by doctor', 'Reminders sent daily at 09:00', 'Records'], head=['Doctor', 'Files', 'Oldest', 'Items'],
  rows=[['Dr. R. Menon', '9', '6 days', 'Unsigned summaries'], ['Dr. P. Joshi', '7', '5 days', 'Op notes, consent scans'], ['Dr. Meera Iyer', '4', '2 days', 'Progress notes'], ['Dr. F. Khan', '3', '1 day', 'Birth details']],
  alerts=[['Birth report due', 'Baby of Priya Shinde · 21 days rule', 'CRS', 'ba'], ['Police request', 'MLC/26/0041 injury certificate', 'MLC', 'br'], ['Retention list', 'Files due for archive', 'Archive', 'bn']]),
'kitchen': dict(role='Dietitian', greet='Good morning, Nisha', sub='Lunch service 12:30 · 112 meals',
  quick=[['Production sheet', 'Diet'], ['Diet orders', 'Diet'], ['Kitchen indent', 'Inventory']],
  kpis=[['Lunch meals', '112', '22 attendants', 'Diet'], ['Special diets', '41', '8 types', 'Diet'], ['Nil by mouth', '4', 'right now', 'Diet'], ['Diet changes', '3', 'today', 'Diet'], ['Assessments due', '5', 'new admissions', 'Diet']],
  q=['Diet changes today', 'Update production before 11:30', 'Diet'], head=['Patient', 'Bed', 'Change', 'Ordered by', 'Time'],
  rows=[['Ravi Kumar', '#W2-204-B', 'Normal → low-salt cardiac', 'Dr. Meera Iyer', '11:05'], ['M. Lal', '#W2-203-A', 'Normal → diabetic 1,800 kcal', 'Dietitian', '10:20'], ['S. Patil', '#W2-201-A', 'Liquid → soft', 'Dr. R. Menon', '09:40']],
  alerts=[['NBM until 14:00', 'P. Rao · do not send lunch', 'NBM', 'br'], ['Complaint', 'Food temperature, Ward 1', 'Quality', 'ba'], ['Rice stock low', '2 days left', 'Store', 'ba']]),
'facility': dict(role='Housekeeping Supervisor', greet='Good morning, Maria', sub='Housekeeping, linen, maintenance and biomedical',
  quick=[['Housekeeping board', 'Facility'], ['Raise ticket', 'Facility'], ['Bed board', 'Beds']],
  kpis=[['Beds to clean', '3', 'target 45 min', 'Facility'], ['Open tickets', '3', '1 high', 'Facility'], ['PM overdue', '1', 'Ventilator V-03', 'Facility'], ['Linen short', '22 pcs', 'from laundry', 'Facility'], ['Waste today', '88 kg', 'handed over', 'Facility']],
  q=['Cleaning queue', 'Beds wait for you before the next admission', 'Facility'], head=['Bed / area', 'Task', 'Waiting', 'Assigned', 'Status'],
  rows=[['#W2-202-B', 'Discharge clean', '40 min', 'Suresh', '~ba:Pending'], ['#PVT-07', 'Terminal clean', '5 min', '-', '~ba:Pending'], ['#ICU-06', 'Isolation clean', '25 min', 'Leela', '~bo:In progress'], ['#W1-105-A', 'Verify cleaned', '38 min', 'You', '~bg:To verify']],
  alerts=[['Bed delaying admission', 'W2-202-B needed by 12:00', 'Urgent', 'br'], ['AMC renewal', 'USG machine, 30 Nov', 'Contract', 'bo'], ['Linen below par', 'Ward 2 bedsheets', 'Linen', 'ba']]),
'quality': dict(role='Quality Manager', greet='Good morning, Dr. Shah', sub='NABH indicators · September published',
  quick=[['Incidents', 'Quality'], ['Indicators', 'Quality'], ['Start audit', 'Quality']],
  kpis=[['Incidents open', '4', '1 new today', 'Quality'], ['Complaints past TAT', '2', 'over 72 h', 'Quality'], ['Indicators missed', '2', 'of 8', 'Quality'], ['NPS', '+62', 'this month', 'Quality'], ['Hand hygiene', '86%', 'target 90%', 'Quality']],
  q=['Open incidents', 'Assign owners and close with corrective actions', 'Quality'], head=['No.', 'Type', 'Where', 'Severity', 'Stage'],
  rows=[['#INC-0192', 'Patient fall', 'Ward 2', '~ba:Moderate', '~bb:Investigation'], ['#INC-0191', 'Medication near miss', 'ICU', '~bn:No harm', '~bo:Action'], ['#INC-0188', 'Needle-stick', 'Laboratory', '~ba:Moderate', '~bo:Follow-up'], ['#INC-0185', 'Equipment failure', 'ICU', '~bn:No harm', '~bg:Ready to close']],
  alerts=[['Falls above target', '1.4 per 1,000 patient days', 'NABH', 'br'], ['VAP rate rising', '3.2 per 1,000 ventilator days', 'Infection', 'ba'], ['SOP review due', 'Fall prevention v2.0', 'Document', 'bn']]),
'crm': dict(role='CRM Executive', greet='Good morning, Pooja', sub='Call centre and outreach',
  quick=[['Call next lead', 'Crm'], ['Book appointment', 'Opd'], ['New campaign', 'Crm']],
  kpis=[['Follow-ups today', '12', 'leads', 'Crm'], ['Calls today', '214', '9 missed', 'Crm'], ['Converted', '31', 'this month', 'Crm'], ['Camp on 12 Oct', '84', 'registered', 'Crm'], ['Renewals due', '63', 'memberships', 'Crm']],
  q=['Leads due today', 'Call in order of interest', 'Crm'], head=['Lead', 'Interest', 'Source', 'Stage', 'Last contact'],
  rows=[['Meena J.', 'Knee replacement', 'Phone', '~bb:New', 'Today 10:41'], ['Prakash S.', 'MRI brain', 'Website', '~bb:New', 'Today 09:47'], ['Divya R.', 'Health check', 'WhatsApp', '~bo:Contacted', 'Yesterday'], ['Rakesh M.', 'Angiography', 'Call centre', '~ba:Counselled', '07 Oct']],
  alerts=[['Missed calls', '2 not called back', 'Calls', 'br'], ['Campaign result', 'HbA1c reminder: 14% booked', 'Campaign', 'bg'], ['Camp kit', 'Confirm BP machines for 12 Oct', 'Camp', 'bn']]),
}
lines = []
for k, d in H.items():
    p = P[k]; name = p['home']
    shutil.copy(os.path.join(S, 'body/_Home.html'), os.path.join(S, 'body/%s.html' % name))
    data = {kk: d[kk] for kk in ['greet', 'sub', 'quick', 'kpis', 'q', 'head', 'rows', 'alerts']}
    js = '  renderVals() {\n    return Object.assign({ nav: this.navItems(%r) }, this.home(%s));\n  }\n' % (name, json.dumps(data, ensure_ascii=False))
    open(os.path.join(S, 'js/%s.js' % name), 'w').write(js)
    lines.append('\t'.join([name, p['name'] + ' home', p['name'] + ' / Home', 'Home · ' + p['name'], p['user'], d['role'], p['init'], k]))
open(os.path.join(S, 'homes.tsv'), 'w').write('\n'.join(lines) + '\n')
print(len(lines), 'homes')
