TITLE = "IPD module overview"
KICKER = "Module deep dive · 2 of 16"
H1 = "IPD: Admission to Discharge"
LEAD = 'From admission advice to a clean bed: estimate, insurance approval, bed allocation, admission, ward care, daily billing, transfers, discharge and claim. Built to match what leading hospital systems offer and to go further on India-specific needs such as cashless insurance and government schemes.'
ALTS = 13
ROLES = 11
LINKS = [('IpdFlow', '1 · End-to-end flow'), ('IpdAltFlows', '2 · Alternate flows'), ('IpdStates', '3 · Status lifecycles'), ('IpdRules', '4 · Rules, messages, reports'), ('IpdConfig', '5 · IPD settings screen'), ('IpdAnalytics', '6 · IPD analytics')]
ROLE_LINKS = [('IpdRolePatient', 'Patient and attendant'), ('IpdRoleAdmissionDesk', 'Admission desk'), ('IpdRoleTpa', 'Insurance desk'), ('IpdRoleBedManager', 'Bed manager'), ('IpdRoleNurse', 'Nurse'), ('IpdRoleDoctor', 'Doctor'), ('IpdRolePharmacy', 'Pharmacy, lab, diet'), ('IpdRoleBilling', 'In-patient billing'), ('IpdRoleHousekeeping', 'Housekeeping'), ('IpdRoleAdmin', 'IPD admin'), ('IpdRoleManagement', 'Management')]
COMPETITORS = ["Indian HMS vendors (MocDoc and others)", "KareXpert Smart Hospital", "Epic Grand Central (enterprise)", "Bahmni (open source)"]
SOURCES = 'Sources: MocDoc blog on in-patient management; Codingclave, Doctors App and OneCity IPD product pages; KareXpert Smart Hospital listings on Capterra and GetApp and the KareXpert emergency blog; Epic Grand Central summaries by IntuitionLabs, Alberta Connect Care and a Northwell (NSUH) 2025 poster; Bahmni wiki Bed Management and IPD pages (CC BY-SA 4.0); IRDAI Master Circular on health insurance (May 2024) as reported by BusinessWorld and The Week. "Other Epic modules" means the feature sits outside Grand Central. Reviewed October 2026.'
DIFF = [('Money never blocks care.', 'Emergencies are admitted first; deposits, top-ups and insurer approvals run alongside, with alerts instead of stopped treatment.'), ('Cashless that keeps time.', 'The insurance desk works to the IRDAI 1-hour and 3-hour clocks, prompts enhancement at 90% and warns about room-rent limits before an upgrade.'), ('The family sees the bill.', 'Attendants see the running bill, deposit and discharge progress on the phone, which cuts disputes at the counter.'), ('Beds as a flow.', 'Bed requests, transfers, expected discharges and cleaning tasks sit on one screen, so a vacated bed is ready in minutes.'), ('Charges post themselves.', 'Room, nursing, oxygen, equipment, diet and visits post from the census, charts and orders; pharmacy returns credit before the final bill.'), ('NABH numbers without registers.', 'Occupancy, length of stay, turnover, discharge time, deaths and LAMA come from time stamps, with formulas shown.')]
HEIGHT = 2720
GROUPS = 7
BENCH = 16
DATA_JS = r"""    var G = [
      ['Admission', [['Admission request from OPD, emergency or doctor', 's'], ['Estimate with financial counselling, e-signed', 'a'], ['Digital consents in English, Hindi, Marathi', 'a'], ['Barcode wristband and attendant pass', 's'], ['Planned admission booking with pre-op checks', 'a'], ['ABHA linking at admission', 'o']]],
      ['Beds and transfers', [['Live bed board by ward and status', 's'], ['Bed categories, tariffs and gender bays', 's'], ['Bed requests with suggested beds', 'a'], ['Reservation with 2-hour expiry', 'a'], ['Transfers and ICU step-up with handover', 's'], ['Expected discharges feed bed planning', 'a'], ['Cleaning tasks with turnaround timer', 'a']]],
      ['Insurance and schemes', [['Policy check and pre-authorisation', 's'], ['IRDAI 1-hour and 3-hour timers', 'o'], ['Enhancement prompt at 90% of approval', 'o'], ['Room-rent limit warning before upgrade', 'o'], ['PM-JAY, CGHS, ECHS and corporate payers', 'a'], ['Claim filing and settlement matching', 'a'], ['Denial to cash conversion', 'a']]],
      ['Ward care', [['Doctor assessment in 24 h, nursing in 2 h', 'a'], ['Daily progress notes and orders', 's'], ['Barcode medicine round (eMAR)', 'a'], ['Vitals with early warning score', 'a'], ['Intake-output, ICU and wound charts', 's'], ['Shift handover (SBAR)', 'a'], ['Diet orders to kitchen', 's'], ['Cross-consultation requests', 's']]],
      ['Billing', [['Daily auto-charges from census and charts', 'a'], ['Running and interim bills', 's'], ['Deposit tracking and top-up alerts', 's'], ['Package billing with extras shown', 's'], ['Pharmacy returns credited before final bill', 'a'], ['Split bill: insurer, patient, corporate', 'a'], ['Running bill on the attendant’s phone', 'o']]],
      ['Discharge', [['Expected discharge date a day ahead', 'a'], ['Discharge summary from the case record', 's'], ['Parallel clearance checklist', 'a'], ['Discharge turnaround tracking', 'o'], ['LAMA, death, transfer-out and absconding flows', 's'], ['Documents on WhatsApp and ABHA', 'o'], ['Follow-up booked automatically', 'a']]],
      ['Analytics and compliance', [['Census, occupancy, length of stay', 's'], ['Turnover rate and interval', 'a'], ['Revenue per occupied bed day', 'a'], ['Readmission within 30 days', 'a'], ['NABH indicators with formulas', 'o'], ['Medico-legal register and locked records', 'a'], ['Full audit of transfers, charges and approvals', 'o']]]
    ];
    var Y = ['Yes', 'bg'], N = ['Not found', 'bn'], P = ['Partly', 'ba'], O = ['Yes', 'bo'], X = ['Other Epic modules', 'bn'];
    var B = [
      ['Admission, transfer and discharge', Y, Y, Y, Y, O], ['Live bed board and occupancy', Y, Y, Y, Y, O], ['Room transfers', Y, Y, Y, Y, O], ['Housekeeping task when a bed is vacated', N, N, Y, N, O],
      ['Predictive capacity or expected discharges', N, N, Y, ['To-be-discharged queue', 'ba'], O], ['Physician orders and nursing notes', Y, N, X, N, O], ['IP bill with department breakdown', Y, N, X, ['Via Odoo', 'ba'], O], ['On-the-spot or interim bills', Y, N, X, N, O],
      ['Insurance and TPA claim management', Y, N, X, N, O], ['Pre-auth with IRDAI time limits', N, N, N, N, O], ['Room-rent limit warning on upgrade', N, N, N, N, O], ['Discharge summary generation', Y, ['Discharge automation', 'ba'], X, N, O],
      ['Running bill visible to family', N, N, N, N, O], ['ABDM and ABHA', ['Vendor claims', 'ba'], N, N, N, O], ['PM-JAY and CGHS packages', N, N, N, N, ['Recorded; portal entry manual', 'ba']], ['Discharge turnaround analytics', N, N, Y, N, O]];
"""
