/** API error codes and their HTTP status (spec "Error format and status codes"). */
export const ERROR_CODES = Object.freeze({
  BAD_REQUEST: 400,
  UNAUTHENTICATED: 401,
  TOKEN_INVALID: 401,
  INVALID_CREDENTIALS: 401,
  TWO_FACTOR_REQUIRED: 401,
  MODULE_NOT_SUBSCRIBED: 402,
  TENANT_READ_ONLY: 402,
  TENANT_SUSPENDED: 402,
  LIMIT_REACHED: 402,
  FORBIDDEN: 403,
  MAKER_CANNOT_CHECK: 403,
  TWO_FACTOR_SETUP_REQUIRED: 403,
  ACCOUNT_LOCKED: 423,
  NOT_FOUND: 404,
  TENANT_NOT_FOUND: 404,
  VERSION_CONFLICT: 409,
  IDEMPOTENCY_IN_PROGRESS: 409,
  POSSIBLE_DUPLICATE: 409,
  VALIDATION_FAILED: 422,
  RATE_LIMITED: 429,
  INTERNAL: 500,
});

export const APPROVAL_PENDING = 'APPROVAL_PENDING';
