/**
 * Generates src/catalog/{screens,panels}.js from the design docs so the menus, routes and role
 * permissions in code always match the UI design:
 *   docs/ui-design/screens.md               screen inventory (route, module, permission)
 *   docs/ui-design/source/parts/panels.json role panels (home, menu, scope)
 * Run: pnpm catalog   (CI fails if the generated files are out of date)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { isPermissionKey, toReadOnly } from '../src/permissions.js';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../../..');
const out = resolve(here, '../src/catalog');

/** Build phase of each module (docs/implementation/PLAN.md section 7). */
const PHASE = {
  CORE: 1,
  OPD: 2,
  IPD: 3,
  NUR: 3,
  LAB: 4,
  RAD: 4,
  PHR: 4,
  INV: 4,
  HRM: 5,
  PAY: 5,
  FIN: 5,
  MRD: 6,
  DIET: 6,
  FAC: 6,
  QLT: 6,
  CRM: 6,
};
const READ_ONLY_PANELS = new Set(['auditor']);

const md = readFileSync(resolve(root, 'docs/ui-design/screens.md'), 'utf8');
const screens = {};
for (const line of md.split('\n')) {
  const cells = line
    .split('|')
    .slice(1, -1)
    .map((c) => c.trim());
  if (cells.length !== 7 || !cells[1].startsWith('boards/')) continue;
  const [title, file, route, role, module, permission, apis] = cells;
  // The 25 role home pages share one route; they are one screen in code.
  const key = title.startsWith('Role home pages') ? 'Home' : basename(file, '.dc.html');
  const app =
    route === '-'
      ? null
      : route.startsWith('console/')
        ? 'console'
        : route.startsWith('www/')
          ? 'www'
          : route.startsWith('portal') || role.toLowerCase().startsWith('patient')
            ? 'portal'
            : 'web';
  const permissions = permission
    .split(',')
    .map((s) => s.trim())
    .filter(isPermissionKey);
  const mod = /^[A-Z]{2,4}$/.test(module) ? module : null;
  screens[key] = {
    title,
    route: route === '-' ? null : route,
    app,
    module: mod,
    permissions,
    role,
    apis:
      apis === '-'
        ? []
        : apis.split(/,\s*(?=[A-Z/]|GET|POST|PUT|PATCH|DELETE)/).map((s) => s.trim()),
    phase: mod ? (PHASE[mod] ?? 1) : 0,
  };
}

const panelsSrc = JSON.parse(
  readFileSync(resolve(root, 'docs/ui-design/source/parts/panels.json'), 'utf8'),
);
const panels = {};
const missing = new Set();
for (const [key, p] of Object.entries(panelsSrc)) {
  const menu = p.menu.map(([group, items]) => ({
    group,
    items: items.map(([label, board]) => {
      const screen = /^Home[A-Z]/.test(board) ? 'Home' : board;
      if (!screens[screen]) missing.add(`${key}: ${screen}`);
      return { label, screen };
    }),
  }));
  // Least privilege by default: a panel gets full rights only on screens where it is the
  // primary role; everything else on its menu is read-only. Each module refines its own
  // action grants when it is built (see the module README).
  const names = [p.name, ...p.roles.split(',')].map((s) => s.trim().toLowerCase()).filter(Boolean);
  const isPrimary = (role) =>
    role
      .split(/,| and /)
      .map((s) => s.trim().toLowerCase())
      .filter(Boolean)
      .some(
        (r) =>
          r === 'all users' ||
          r === 'each role' ||
          names.some((n) => n.includes(r) || r.includes(n)),
      );
  const perms = new Set();
  for (const g of menu) {
    for (const it of g.items) {
      const s = screens[it.screen];
      for (const k of s?.permissions ?? [])
        perms.add(READ_ONLY_PANELS.has(key) || !isPrimary(s.role) ? toReadOnly(k) : k);
    }
  }
  let permissions = [...perms];
  if (key === 'superadmin') permissions = ['*'];
  if (READ_ONLY_PANELS.has(key)) permissions.push('audit:log:read', 'audit:log:export');
  permissions.push('myspace:*');
  const home = /^Home[A-Z]/.test(p.home) ? 'Home' : p.home;
  panels[key] = {
    name: p.name,
    roles: p.roles,
    home,
    scope: p.scope,
    readOnly: READ_ONLY_PANELS.has(key),
    menu,
    permissions: [...new Set(permissions)].sort(),
  };
}

const header =
  '// Generated by packages/shared/scripts/gen-catalog.js from docs/ui-design. Do not edit.\n';
writeFileSync(
  resolve(out, 'screens.js'),
  `${header}export const SCREENS = Object.freeze(${JSON.stringify(screens, null, 2)});\n`,
);
writeFileSync(
  resolve(out, 'panels.js'),
  `${header}export const PANELS = Object.freeze(${JSON.stringify(panels, null, 2)});\n`,
);
console.log(`screens: ${Object.keys(screens).length}, panels: ${Object.keys(panels).length}`);
if (missing.size)
  console.log(`menu items without a screen row (shown as planned): ${[...missing].join('; ')}`);
