// Generated by packages/shared/scripts/gen-catalog.js from docs/ui-design. Do not edit.
export const PANELS = Object.freeze({
  "superadmin": {
    "name": "Super Admin",
    "roles": "Hospital Super Admin",
    "home": "Dashboard",
    "scope": "Whole hospital, all branches",
    "readOnly": false,
    "menu": [
      {
        "group": "Overview",
        "items": [
          {
            "label": "Dashboard",
            "screen": "Dashboard"
          },
          {
            "label": "OPD Analytics",
            "screen": "OpdAnalytics"
          },
          {
            "label": "IPD Analytics",
            "screen": "IpdAnalytics"
          },
          {
            "label": "Billing Analytics",
            "screen": "BillAnalytics"
          },
          {
            "label": "Lab Analytics",
            "screen": "LabAnalytics"
          },
          {
            "label": "Approvals",
            "screen": "Approvals"
          },
          {
            "label": "Reports",
            "screen": "Reports"
          },
          {
            "label": "Audit Log",
            "screen": "AuditLog"
          }
        ]
      },
      {
        "group": "Patients",
        "items": [
          {
            "label": "Patients",
            "screen": "Patients"
          },
          {
            "label": "Patient Profile",
            "screen": "PatientProfile"
          },
          {
            "label": "Front Office",
            "screen": "FrontOffice"
          },
          {
            "label": "OPD Check-in",
            "screen": "OpdCheckin"
          },
          {
            "label": "Appointments",
            "screen": "Opd"
          },
          {
            "label": "Admissions",
            "screen": "Admission"
          },
          {
            "label": "Bed Board",
            "screen": "Beds"
          },
          {
            "label": "Bed Requests",
            "screen": "IpdBedRequests"
          },
          {
            "label": "Discharge Desk",
            "screen": "Discharge"
          }
        ]
      },
      {
        "group": "Clinical",
        "items": [
          {
            "label": "Consultation",
            "screen": "Consult"
          },
          {
            "label": "OPD Triage",
            "screen": "OpdTriage"
          },
          {
            "label": "In-patient Rounds",
            "screen": "IpdRounds"
          },
          {
            "label": "Nursing Station",
            "screen": "Nursing"
          },
          {
            "label": "Rosters",
            "screen": "Roster"
          }
        ]
      },
      {
        "group": "Diagnostics",
        "items": [
          {
            "label": "Laboratory",
            "screen": "Lab"
          },
          {
            "label": "Sample Collection",
            "screen": "LabSample"
          },
          {
            "label": "Lab Settings",
            "screen": "LabConfig"
          },
          {
            "label": "Radiology",
            "screen": "Radiology"
          },
          {
            "label": "Pharmacy",
            "screen": "Pharmacy"
          }
        ]
      },
      {
        "group": "Business",
        "items": [
          {
            "label": "Billing",
            "screen": "Billing"
          },
          {
            "label": "Shifts and Day-end",
            "screen": "BillShift"
          },
          {
            "label": "In-patient Bills",
            "screen": "IpdBill"
          },
          {
            "label": "Insurance Desk",
            "screen": "IpdTpa"
          },
          {
            "label": "Corporate and Credit",
            "screen": "BillCorporate"
          },
          {
            "label": "Finance",
            "screen": "Finance"
          },
          {
            "label": "Inventory",
            "screen": "Inventory"
          },
          {
            "label": "HR",
            "screen": "Hr"
          },
          {
            "label": "Payroll",
            "screen": "Payroll"
          }
        ]
      },
      {
        "group": "Support",
        "items": [
          {
            "label": "Medical Records",
            "screen": "Records"
          },
          {
            "label": "Diet & Kitchen",
            "screen": "Diet"
          },
          {
            "label": "Facility",
            "screen": "Facility"
          },
          {
            "label": "Quality",
            "screen": "Quality"
          },
          {
            "label": "CRM",
            "screen": "Crm"
          }
        ]
      },
      {
        "group": "Settings",
        "items": [
          {
            "label": "Hospital Settings",
            "screen": "Settings"
          },
          {
            "label": "Users",
            "screen": "Users"
          },
          {
            "label": "Roles & Access",
            "screen": "Roles"
          },
          {
            "label": "Departments",
            "screen": "Departments"
          },
          {
            "label": "OPD Settings",
            "screen": "OpdConfig"
          },
          {
            "label": "IPD Settings",
            "screen": "IpdConfig"
          },
          {
            "label": "Billing Settings",
            "screen": "BillConfig"
          },
          {
            "label": "Subscription",
            "screen": "Subscription"
          }
        ]
      },
      {
        "group": "Personal",
        "items": [
          {
            "label": "My Space",
            "screen": "MySpace"
          }
        ]
      }
    ],
    "permissions": [
      "*",
      "myspace:*"
    ]
  },
  "admin": {
    "name": "Hospital Admin",
    "roles": "Hospital Admin",
    "home": "Home",
    "scope": "Branch",
    "readOnly": false,
    "menu": [
      {
        "group": "Overview",
        "items": [
          {
            "label": "Home",
            "screen": "Home"
          },
          {
            "label": "Approvals",
            "screen": "Approvals"
          },
          {
            "label": "Reports",
            "screen": "Reports"
          },
          {
            "label": "Finance",
            "screen": "Finance"
          }
        ]
      },
      {
        "group": "Operations",
        "items": [
          {
            "label": "Patients",
            "screen": "Patients"
          },
          {
            "label": "Front Office",
            "screen": "FrontOffice"
          },
          {
            "label": "Bed Board",
            "screen": "Beds"
          },
          {
            "label": "Inventory",
            "screen": "Inventory"
          },
          {
            "label": "Appointments",
            "screen": "Opd"
          },
          {
            "label": "Admissions",
            "screen": "Admission"
          },
          {
            "label": "Nursing Station",
            "screen": "Nursing"
          },
          {
            "label": "HR",
            "screen": "Hr"
          }
        ]
      },
      {
        "group": "Settings",
        "items": [
          {
            "label": "Hospital Settings",
            "screen": "Settings"
          },
          {
            "label": "Users",
            "screen": "Users"
          },
          {
            "label": "Roles & Access",
            "screen": "Roles"
          },
          {
            "label": "Departments",
            "screen": "Departments"
          },
          {
            "label": "OPD Settings",
            "screen": "OpdConfig"
          },
          {
            "label": "IPD Settings",
            "screen": "IpdConfig"
          },
          {
            "label": "Billing Settings",
            "screen": "BillConfig"
          }
        ]
      },
      {
        "group": "Services",
        "items": [
          {
            "label": "Medical Records",
            "screen": "Records"
          },
          {
            "label": "Diet & Kitchen",
            "screen": "Diet"
          },
          {
            "label": "Facility",
            "screen": "Facility"
          },
          {
            "label": "Quality",
            "screen": "Quality"
          },
          {
            "label": "CRM",
            "screen": "Crm"
          }
        ]
      },
      {
        "group": "Departments setup",
        "items": [
          {
            "label": "Laboratory",
            "screen": "Lab"
          },
          {
            "label": "Radiology",
            "screen": "Radiology"
          },
          {
            "label": "Pharmacy",
            "screen": "Pharmacy"
          }
        ]
      },
      {
        "group": "Personal",
        "items": [
          {
            "label": "My Space",
            "screen": "MySpace"
          }
        ]
      }
    ],
    "permissions": [
      "approvals:inbox:read",
      "billing:settings:*",
      "crm:*:read",
      "diet:*:read",
      "facility:*:read",
      "finance:*:read",
      "frontoffice:*:read",
      "hr:*:read",
      "inventory:*:read",
      "ipd:admission:read",
      "ipd:bed:read",
      "ipd:settings:*",
      "lab:*:read",
      "mrd:*:read",
      "myspace:*",
      "nursing:*:read",
      "opd:appointment:read",
      "opd:schedule:*",
      "opd:settings:*",
      "patients:patient:read",
      "pharmacy:*:read",
      "quality:*:read",
      "rad:*:read",
      "settings:hospital:read",
      "settings:master:*",
      "settings:role:read",
      "settings:user:*"
    ]
  },
  "medsupt": {
    "name": "Medical Superintendent",
    "roles": "Medical Superintendent",
    "home": "Home",
    "scope": "Branch, clinical",
    "readOnly": false,
    "menu": [
      {
        "group": "Overview",
        "items": [
          {
            "label": "Home",
            "screen": "Home"
          },
          {
            "label": "OPD Analytics",
            "screen": "OpdAnalytics"
          },
          {
            "label": "IPD Analytics",
            "screen": "IpdAnalytics"
          },
          {
            "label": "Lab Analytics",
            "screen": "LabAnalytics"
          },
          {
            "label": "Approvals",
            "screen": "Approvals"
          },
          {
            "label": "Reports",
            "screen": "Reports"
          }
        ]
      },
      {
        "group": "Clinical",
        "items": [
          {
            "label": "Bed Board",
            "screen": "Beds"
          },
          {
            "label": "Bed Requests",
            "screen": "IpdBedRequests"
          },
          {
            "label": "Discharge Desk",
            "screen": "Discharge"
          },
          {
            "label": "Nursing Station",
            "screen": "Nursing"
          },
          {
            "label": "Rosters",
            "screen": "Roster"
          }
        ]
      },
      {
        "group": "Governance",
        "items": [
          {
            "label": "Medical Records",
            "screen": "Records"
          },
          {
            "label": "Quality",
            "screen": "Quality"
          }
        ]
      },
      {
        "group": "Services (read)",
        "items": [
          {
            "label": "Diet & Kitchen",
            "screen": "Diet"
          },
          {
            "label": "Facility",
            "screen": "Facility"
          },
          {
            "label": "CRM",
            "screen": "Crm"
          }
        ]
      },
      {
        "group": "Personal",
        "items": [
          {
            "label": "My Space",
            "screen": "MySpace"
          }
        ]
      }
    ],
    "permissions": [
      "approvals:inbox:read",
      "crm:*:read",
      "diet:*:read",
      "facility:*:read",
      "hr:roster:read",
      "ipd:bed:read",
      "ipd:discharge:read",
      "mrd:*:read",
      "myspace:*",
      "nursing:*:read",
      "quality:*:read",
      "reports:ipd:read",
      "reports:lab:read",
      "reports:opd:read"
    ]
  },
  "doctor": {
    "name": "Doctor",
    "roles": "Consultant, Resident",
    "home": "Home",
    "scope": "Own patients and department",
    "readOnly": false,
    "menu": [
      {
        "group": "My day",
        "items": [
          {
            "label": "Home",
            "screen": "Home"
          },
          {
            "label": "OPD Consultation",
            "screen": "Consult"
          },
          {
            "label": "In-patient Rounds",
            "screen": "IpdRounds"
          },
          {
            "label": "Discharge Desk",
            "screen": "Discharge"
          }
        ]
      },
      {
        "group": "Patients",
        "items": [
          {
            "label": "Patient Profile",
            "screen": "PatientProfile"
          },
          {
            "label": "Bed Board",
            "screen": "Beds"
          }
        ]
      },
      {
        "group": "Results",
        "items": [
          {
            "label": "Laboratory",
            "screen": "Lab"
          },
          {
            "label": "Radiology",
            "screen": "Radiology"
          },
          {
            "label": "Microbiology",
            "screen": "LabMicro"
          },
          {
            "label": "Histopathology",
            "screen": "LabHisto"
          }
        ]
      },
      {
        "group": "Records and orders",
        "items": [
          {
            "label": "Medical Records",
            "screen": "Records"
          },
          {
            "label": "Diet Orders",
            "screen": "Diet"
          },
          {
            "label": "CRM",
            "screen": "Crm"
          }
        ]
      },
      {
        "group": "Personal",
        "items": [
          {
            "label": "My Space",
            "screen": "MySpace"
          }
        ]
      }
    ],
    "permissions": [
      "crm:*:read",
      "diet:*:read",
      "ipd:bed:read",
      "ipd:discharge:*",
      "ipd:note:write",
      "lab:*:read",
      "lab:histo:read",
      "lab:micro:read",
      "mrd:*:read",
      "myspace:*",
      "opd:consultation:write",
      "orders:*",
      "patients:patient:read",
      "rad:*:read"
    ]
  },
  "hod": {
    "name": "Head of Department",
    "roles": "Department Head (HOD)",
    "home": "Home",
    "scope": "Own department (Cardiology)",
    "readOnly": false,
    "menu": [
      {
        "group": "My department",
        "items": [
          {
            "label": "Home",
            "screen": "Home"
          },
          {
            "label": "Approvals",
            "screen": "Approvals"
          },
          {
            "label": "Rosters",
            "screen": "Roster"
          },
          {
            "label": "Reports",
            "screen": "Reports"
          }
        ]
      },
      {
        "group": "Clinical",
        "items": [
          {
            "label": "OPD Consultation",
            "screen": "Consult"
          },
          {
            "label": "In-patient Rounds",
            "screen": "IpdRounds"
          },
          {
            "label": "Discharge Desk",
            "screen": "Discharge"
          },
          {
            "label": "Bed Board",
            "screen": "Beds"
          }
        ]
      },
      {
        "group": "Department",
        "items": [
          {
            "label": "Indents and Stock",
            "screen": "Inventory"
          },
          {
            "label": "Quality",
            "screen": "Quality"
          }
        ]
      },
      {
        "group": "Personal",
        "items": [
          {
            "label": "My Space",
            "screen": "MySpace"
          }
        ]
      }
    ],
    "permissions": [
      "approvals:inbox:read",
      "hr:roster:read",
      "inventory:*:read",
      "ipd:bed:read",
      "ipd:discharge:read",
      "ipd:note:read",
      "myspace:*",
      "opd:consultation:read",
      "orders:*:read",
      "quality:*:read"
    ]
  },
  "clinic": {
    "name": "Clinic (one-screen mode)",
    "roles": "Clinic doctor who is also the admin",
    "home": "ClinicDesk",
    "scope": "Whole clinic",
    "readOnly": false,
    "menu": [
      {
        "group": "Clinic",
        "items": [
          {
            "label": "Today's Clinic",
            "screen": "ClinicDesk"
          },
          {
            "label": "Appointments",
            "screen": "Opd"
          },
          {
            "label": "Patients",
            "screen": "Patients"
          },
          {
            "label": "Billing",
            "screen": "Billing"
          },
          {
            "label": "Pharmacy",
            "screen": "Pharmacy"
          }
        ]
      },
      {
        "group": "Setup",
        "items": [
          {
            "label": "Clinic Settings",
            "screen": "Settings"
          },
          {
            "label": "Users",
            "screen": "Users"
          },
          {
            "label": "Reports",
            "screen": "Reports"
          },
          {
            "label": "Subscription",
            "screen": "Subscription"
          }
        ]
      },
      {
        "group": "Personal",
        "items": [
          {
            "label": "My Space",
            "screen": "MySpace"
          }
        ]
      }
    ],
    "permissions": [
      "billing:*:read",
      "billing:bill:create",
      "myspace:*",
      "opd:*",
      "opd:appointment:read",
      "patients:patient:read",
      "pharmacy:*:read",
      "settings:hospital:read",
      "settings:subscription:read",
      "settings:user:*"
    ]
  },
  "nurse": {
    "name": "Staff Nurse",
    "roles": "Staff Nurse",
    "home": "Home",
    "scope": "Assigned ward",
    "readOnly": false,
    "menu": [
      {
        "group": "My ward",
        "items": [
          {
            "label": "Home",
            "screen": "Home"
          },
          {
            "label": "Nursing Station",
            "screen": "Nursing"
          },
          {
            "label": "Bed Board",
            "screen": "Beds"
          },
          {
            "label": "Patient Profile",
            "screen": "PatientProfile"
          }
        ]
      },
      {
        "group": "OPD",
        "items": [
          {
            "label": "OPD Triage",
            "screen": "OpdTriage"
          }
        ]
      },
      {
        "group": "Requests",
        "items": [
          {
            "label": "Diet Orders",
            "screen": "Diet"
          },
          {
            "label": "Tickets and Transport",
            "screen": "Facility"
          },
          {
            "label": "Report Incident",
            "screen": "Quality"
          }
        ]
      },
      {
        "group": "Results",
        "items": [
          {
            "label": "Laboratory",
            "screen": "Lab"
          },
          {
            "label": "Radiology",
            "screen": "Radiology"
          },
          {
            "label": "Medical Records",
            "screen": "Records"
          },
          {
            "label": "Sample Collection",
            "screen": "LabSample"
          }
        ]
      },
      {
        "group": "Personal",
        "items": [
          {
            "label": "My Space",
            "screen": "MySpace"
          }
        ]
      }
    ],
    "permissions": [
      "diet:*:read",
      "facility:*:read",
      "ipd:bed:read",
      "lab:*:read",
      "lab:sample:*",
      "mrd:*:read",
      "myspace:*",
      "nursing:*",
      "opd:vitals:create",
      "patients:patient:read",
      "quality:*:read",
      "rad:*:read"
    ]
  },
  "wardincharge": {
    "name": "Ward In-charge",
    "roles": "Ward In-charge (Sister), Nursing Superintendent",
    "home": "Home",
    "scope": "Ward (Nursing Superintendent: all wards in the branch)",
    "readOnly": false,
    "menu": [
      {
        "group": "My ward",
        "items": [
          {
            "label": "Home",
            "screen": "Home"
          },
          {
            "label": "Nursing Station",
            "screen": "Nursing"
          },
          {
            "label": "Rosters",
            "screen": "Roster"
          },
          {
            "label": "Bed Board",
            "screen": "Beds"
          },
          {
            "label": "Bed Requests",
            "screen": "IpdBedRequests"
          }
        ]
      },
      {
        "group": "Requests",
        "items": [
          {
            "label": "Approvals",
            "screen": "Approvals"
          },
          {
            "label": "Store Indents",
            "screen": "Inventory"
          },
          {
            "label": "Facility",
            "screen": "Facility"
          },
          {
            "label": "Quality",
            "screen": "Quality"
          }
        ]
      },
      {
        "group": "Personal",
        "items": [
          {
            "label": "My Space",
            "screen": "MySpace"
          }
        ]
      }
    ],
    "permissions": [
      "approvals:inbox:read",
      "facility:*:read",
      "hr:roster:write",
      "inventory:*:read",
      "ipd:bed:allocate",
      "ipd:bed:read",
      "myspace:*",
      "nursing:*:read",
      "quality:*:read"
    ]
  },
  "frontoffice": {
    "name": "Front Office",
    "roles": "Front Office, Admission Desk",
    "home": "Home",
    "scope": "Branch",
    "readOnly": false,
    "menu": [
      {
        "group": "Front desk",
        "items": [
          {
            "label": "Home",
            "screen": "Home"
          },
          {
            "label": "Front Office",
            "screen": "FrontOffice"
          },
          {
            "label": "OPD Check-in",
            "screen": "OpdCheckin"
          },
          {
            "label": "Register Patient",
            "screen": "Patients"
          },
          {
            "label": "Patient Profile",
            "screen": "PatientProfile"
          },
          {
            "label": "Appointments",
            "screen": "Opd"
          }
        ]
      },
      {
        "group": "In-patients",
        "items": [
          {
            "label": "Admissions",
            "screen": "Admission"
          },
          {
            "label": "Bed Board",
            "screen": "Beds"
          },
          {
            "label": "Bed Requests",
            "screen": "IpdBedRequests"
          }
        ]
      },
      {
        "group": "Records and CRM",
        "items": [
          {
            "label": "Medical Records",
            "screen": "Records"
          },
          {
            "label": "CRM",
            "screen": "Crm"
          }
        ]
      },
      {
        "group": "Personal",
        "items": [
          {
            "label": "My Space",
            "screen": "MySpace"
          }
        ]
      }
    ],
    "permissions": [
      "crm:*:read",
      "frontoffice:*",
      "ipd:admission:create",
      "ipd:bed:allocate",
      "ipd:bed:read",
      "mrd:*:read",
      "myspace:*",
      "opd:appointment:*",
      "opd:visit:create",
      "patients:patient:create",
      "patients:patient:read"
    ]
  },
  "security": {
    "name": "Security Desk",
    "roles": "Security Desk",
    "home": "Home",
    "scope": "Gate and ward entrances",
    "readOnly": false,
    "menu": [
      {
        "group": "Gate",
        "items": [
          {
            "label": "Home",
            "screen": "Home"
          },
          {
            "label": "Visitors and Passes",
            "screen": "FrontOffice"
          },
          {
            "label": "Bed Board",
            "screen": "Beds"
          }
        ]
      },
      {
        "group": "Requests",
        "items": [
          {
            "label": "Tickets",
            "screen": "Facility"
          },
          {
            "label": "Report Incident",
            "screen": "Quality"
          }
        ]
      },
      {
        "group": "Personal",
        "items": [
          {
            "label": "My Space",
            "screen": "MySpace"
          }
        ]
      }
    ],
    "permissions": [
      "facility:*:read",
      "frontoffice:*:read",
      "ipd:bed:read",
      "myspace:*",
      "quality:*:read"
    ]
  },
  "cashier": {
    "name": "Cashier",
    "roles": "Cashier",
    "home": "Home",
    "scope": "Own counter",
    "readOnly": false,
    "menu": [
      {
        "group": "Counter",
        "items": [
          {
            "label": "Home",
            "screen": "Home"
          },
          {
            "label": "Billing Counter",
            "screen": "Billing"
          },
          {
            "label": "Cashier Shift",
            "screen": "BillShift"
          },
          {
            "label": "In-patient Bills",
            "screen": "IpdBill"
          },
          {
            "label": "Find Patient",
            "screen": "PatientProfile"
          }
        ]
      },
      {
        "group": "Reports",
        "items": [
          {
            "label": "Collection Reports",
            "screen": "Reports"
          }
        ]
      },
      {
        "group": "Lookups (read)",
        "items": [
          {
            "label": "Laboratory",
            "screen": "Lab"
          },
          {
            "label": "Radiology",
            "screen": "Radiology"
          },
          {
            "label": "Pharmacy",
            "screen": "Pharmacy"
          }
        ]
      },
      {
        "group": "Personal",
        "items": [
          {
            "label": "My Space",
            "screen": "MySpace"
          }
        ]
      }
    ],
    "permissions": [
      "billing:*",
      "billing:ip:*",
      "billing:shift:*",
      "lab:*:read",
      "myspace:*",
      "patients:patient:read",
      "pharmacy:*:read",
      "rad:*:read"
    ]
  },
  "billingmgr": {
    "name": "Billing Manager",
    "roles": "Billing Manager",
    "home": "Home",
    "scope": "Branch billing",
    "readOnly": false,
    "menu": [
      {
        "group": "Billing",
        "items": [
          {
            "label": "Home",
            "screen": "Home"
          },
          {
            "label": "Billing",
            "screen": "Billing"
          },
          {
            "label": "Shifts and Day-end",
            "screen": "BillShift"
          },
          {
            "label": "In-patient Bills",
            "screen": "IpdBill"
          },
          {
            "label": "Insurance Desk",
            "screen": "IpdTpa"
          },
          {
            "label": "Corporate and Credit",
            "screen": "BillCorporate"
          },
          {
            "label": "Discharge Desk",
            "screen": "Discharge"
          },
          {
            "label": "Approvals",
            "screen": "Approvals"
          }
        ]
      },
      {
        "group": "Reports",
        "items": [
          {
            "label": "Reports",
            "screen": "Reports"
          },
          {
            "label": "Billing Analytics",
            "screen": "BillAnalytics"
          }
        ]
      },
      {
        "group": "Finance (read)",
        "items": [
          {
            "label": "Finance",
            "screen": "Finance"
          }
        ]
      },
      {
        "group": "Lookups (read)",
        "items": [
          {
            "label": "Laboratory",
            "screen": "Lab"
          },
          {
            "label": "Radiology",
            "screen": "Radiology"
          },
          {
            "label": "Pharmacy",
            "screen": "Pharmacy"
          }
        ]
      },
      {
        "group": "Personal",
        "items": [
          {
            "label": "My Space",
            "screen": "MySpace"
          }
        ]
      }
    ],
    "permissions": [
      "approvals:inbox:read",
      "billing:*:read",
      "billing:corporate:*",
      "billing:ip:read",
      "billing:shift:*",
      "finance:*:read",
      "ipd:discharge:*",
      "ipd:preauth:*",
      "lab:*:read",
      "myspace:*",
      "pharmacy:*:read",
      "rad:*:read",
      "reports:billing:read"
    ]
  },
  "tpa": {
    "name": "Insurance Desk",
    "roles": "Insurance Desk (TPA Coordinator)",
    "home": "Home",
    "scope": "Branch, insured and scheme patients",
    "readOnly": false,
    "menu": [
      {
        "group": "Insurance",
        "items": [
          {
            "label": "Home",
            "screen": "Home"
          },
          {
            "label": "Insurance Desk",
            "screen": "IpdTpa"
          },
          {
            "label": "In-patient Bills",
            "screen": "IpdBill"
          },
          {
            "label": "Discharge Desk",
            "screen": "Discharge"
          }
        ]
      },
      {
        "group": "Patients (read)",
        "items": [
          {
            "label": "Admissions",
            "screen": "Admission"
          },
          {
            "label": "Patient Profile",
            "screen": "PatientProfile"
          }
        ]
      },
      {
        "group": "Reports",
        "items": [
          {
            "label": "Reports",
            "screen": "Reports"
          }
        ]
      },
      {
        "group": "Personal",
        "items": [
          {
            "label": "My Space",
            "screen": "MySpace"
          }
        ]
      }
    ],
    "permissions": [
      "billing:ip:read",
      "ipd:admission:read",
      "ipd:discharge:read",
      "ipd:preauth:read",
      "myspace:*",
      "patients:patient:read"
    ]
  },
  "lab": {
    "name": "Laboratory",
    "roles": "Lab Technician, Pathologist",
    "home": "Home",
    "scope": "Laboratory",
    "readOnly": false,
    "menu": [
      {
        "group": "Laboratory",
        "items": [
          {
            "label": "Home",
            "screen": "Home"
          },
          {
            "label": "Worklists",
            "screen": "Lab"
          },
          {
            "label": "Sample Collection",
            "screen": "LabSample"
          },
          {
            "label": "Quality Control",
            "screen": "LabQC"
          },
          {
            "label": "Microbiology",
            "screen": "LabMicro"
          },
          {
            "label": "Histopathology",
            "screen": "LabHisto"
          },
          {
            "label": "Lab Settings",
            "screen": "LabConfig"
          },
          {
            "label": "Lab Analytics",
            "screen": "LabAnalytics"
          },
          {
            "label": "Patient Profile",
            "screen": "PatientProfile"
          }
        ]
      },
      {
        "group": "Requests",
        "items": [
          {
            "label": "Store Indents",
            "screen": "Inventory"
          },
          {
            "label": "Quality",
            "screen": "Quality"
          }
        ]
      },
      {
        "group": "Personal",
        "items": [
          {
            "label": "My Space",
            "screen": "MySpace"
          }
        ]
      }
    ],
    "permissions": [
      "inventory:*:read",
      "lab:*",
      "lab:histo:*",
      "lab:micro:read",
      "lab:qc:*",
      "lab:sample:read",
      "lab:settings:read",
      "myspace:*",
      "patients:patient:read",
      "quality:*:read",
      "reports:lab:read"
    ]
  },
  "phlebotomist": {
    "name": "Home Collection",
    "roles": "Home Collection Phlebotomist",
    "home": "Home",
    "scope": "Assigned area, own visits",
    "readOnly": false,
    "menu": [
      {
        "group": "Visits",
        "items": [
          {
            "label": "Home",
            "screen": "Home"
          },
          {
            "label": "Laboratory",
            "screen": "Lab"
          },
          {
            "label": "Sample Collection",
            "screen": "LabSample"
          }
        ]
      },
      {
        "group": "Personal",
        "items": [
          {
            "label": "My Space",
            "screen": "MySpace"
          }
        ]
      }
    ],
    "permissions": [
      "lab:*:read",
      "lab:sample:read",
      "myspace:*"
    ]
  },
  "radiology": {
    "name": "Radiology",
    "roles": "Radiology Technician, Radiologist",
    "home": "Home",
    "scope": "Radiology",
    "readOnly": false,
    "menu": [
      {
        "group": "Radiology",
        "items": [
          {
            "label": "Home",
            "screen": "Home"
          },
          {
            "label": "Worklist and Reporting",
            "screen": "Radiology"
          },
          {
            "label": "Patient Profile",
            "screen": "PatientProfile"
          }
        ]
      },
      {
        "group": "Requests",
        "items": [
          {
            "label": "Equipment Tickets",
            "screen": "Facility"
          }
        ]
      },
      {
        "group": "Personal",
        "items": [
          {
            "label": "My Space",
            "screen": "MySpace"
          }
        ]
      }
    ],
    "permissions": [
      "facility:*:read",
      "myspace:*",
      "patients:patient:read",
      "rad:*"
    ]
  },
  "pharmacy": {
    "name": "Pharmacy",
    "roles": "Pharmacist, Pharmacy In-charge",
    "home": "Home",
    "scope": "Pharmacy stores",
    "readOnly": false,
    "menu": [
      {
        "group": "Pharmacy",
        "items": [
          {
            "label": "Home",
            "screen": "Home"
          },
          {
            "label": "Dispensing",
            "screen": "Pharmacy"
          },
          {
            "label": "Stock",
            "screen": "Inventory"
          },
          {
            "label": "Counter Shift",
            "screen": "BillShift"
          }
        ]
      },
      {
        "group": "Reports",
        "items": [
          {
            "label": "Reports",
            "screen": "Reports"
          }
        ]
      },
      {
        "group": "Patients (read)",
        "items": [
          {
            "label": "Appointments",
            "screen": "Opd"
          },
          {
            "label": "Bed Board",
            "screen": "Beds"
          }
        ]
      },
      {
        "group": "Personal",
        "items": [
          {
            "label": "My Space",
            "screen": "MySpace"
          }
        ]
      }
    ],
    "permissions": [
      "billing:shift:read",
      "inventory:*:read",
      "ipd:bed:read",
      "myspace:*",
      "opd:appointment:read",
      "pharmacy:*"
    ]
  },
  "store": {
    "name": "Store and Purchase",
    "roles": "Store Keeper, Purchase Manager",
    "home": "Home",
    "scope": "Stores",
    "readOnly": false,
    "menu": [
      {
        "group": "Stores",
        "items": [
          {
            "label": "Home",
            "screen": "Home"
          },
          {
            "label": "Inventory",
            "screen": "Inventory"
          },
          {
            "label": "Approvals",
            "screen": "Approvals"
          }
        ]
      },
      {
        "group": "Reports",
        "items": [
          {
            "label": "Reports",
            "screen": "Reports"
          }
        ]
      },
      {
        "group": "Finance (read)",
        "items": [
          {
            "label": "Finance",
            "screen": "Finance"
          }
        ]
      },
      {
        "group": "Pharmacy stock",
        "items": [
          {
            "label": "Pharmacy",
            "screen": "Pharmacy"
          }
        ]
      },
      {
        "group": "Personal",
        "items": [
          {
            "label": "My Space",
            "screen": "MySpace"
          }
        ]
      }
    ],
    "permissions": [
      "approvals:inbox:read",
      "finance:*:read",
      "inventory:*",
      "myspace:*",
      "pharmacy:*:read"
    ]
  },
  "hr": {
    "name": "HR",
    "roles": "HR Manager, HR Executive",
    "home": "Home",
    "scope": "All employees",
    "readOnly": false,
    "menu": [
      {
        "group": "People",
        "items": [
          {
            "label": "Home",
            "screen": "Home"
          },
          {
            "label": "HR and Attendance",
            "screen": "Hr"
          },
          {
            "label": "Rosters",
            "screen": "Roster"
          },
          {
            "label": "Payroll",
            "screen": "Payroll"
          }
        ]
      },
      {
        "group": "Work",
        "items": [
          {
            "label": "Approvals",
            "screen": "Approvals"
          },
          {
            "label": "Reports",
            "screen": "Reports"
          }
        ]
      },
      {
        "group": "Personal",
        "items": [
          {
            "label": "My Space",
            "screen": "MySpace"
          }
        ]
      }
    ],
    "permissions": [
      "approvals:inbox:read",
      "hr:*",
      "hr:roster:read",
      "myspace:*",
      "payroll:*:read"
    ]
  },
  "payroll": {
    "name": "Payroll",
    "roles": "Payroll Officer",
    "home": "Home",
    "scope": "Payroll entity",
    "readOnly": false,
    "menu": [
      {
        "group": "Payroll",
        "items": [
          {
            "label": "Home",
            "screen": "Home"
          },
          {
            "label": "Payroll Run",
            "screen": "Payroll"
          },
          {
            "label": "Attendance",
            "screen": "Hr"
          }
        ]
      },
      {
        "group": "Reports",
        "items": [
          {
            "label": "Reports",
            "screen": "Reports"
          }
        ]
      },
      {
        "group": "Finance (read)",
        "items": [
          {
            "label": "Finance",
            "screen": "Finance"
          }
        ]
      },
      {
        "group": "Personal",
        "items": [
          {
            "label": "My Space",
            "screen": "MySpace"
          }
        ]
      }
    ],
    "permissions": [
      "finance:*:read",
      "hr:*:read",
      "myspace:*",
      "payroll:*"
    ]
  },
  "accounts": {
    "name": "Accounts",
    "roles": "Accountant, Finance Controller",
    "home": "Home",
    "scope": "Legal entity",
    "readOnly": false,
    "menu": [
      {
        "group": "Finance",
        "items": [
          {
            "label": "Home",
            "screen": "Home"
          },
          {
            "label": "Finance",
            "screen": "Finance"
          },
          {
            "label": "Approvals",
            "screen": "Approvals"
          },
          {
            "label": "Shifts and Day-end",
            "screen": "BillShift"
          }
        ]
      },
      {
        "group": "Source modules",
        "items": [
          {
            "label": "Billing",
            "screen": "Billing"
          },
          {
            "label": "Payroll",
            "screen": "Payroll"
          },
          {
            "label": "Inventory",
            "screen": "Inventory"
          },
          {
            "label": "In-patient Bills",
            "screen": "IpdBill"
          },
          {
            "label": "Pharmacy",
            "screen": "Pharmacy"
          }
        ]
      },
      {
        "group": "Reports",
        "items": [
          {
            "label": "Reports",
            "screen": "Reports"
          },
          {
            "label": "Billing Analytics",
            "screen": "BillAnalytics"
          }
        ]
      },
      {
        "group": "Personal",
        "items": [
          {
            "label": "My Space",
            "screen": "MySpace"
          }
        ]
      }
    ],
    "permissions": [
      "approvals:inbox:read",
      "billing:*:read",
      "billing:ip:read",
      "billing:shift:read",
      "finance:*",
      "inventory:*:read",
      "myspace:*",
      "payroll:*:read",
      "pharmacy:*:read",
      "reports:billing:read"
    ]
  },
  "auditor": {
    "name": "Auditor",
    "roles": "Auditor (internal or statutory), read-only",
    "home": "Home",
    "scope": "Whole hospital, read-only",
    "readOnly": true,
    "menu": [
      {
        "group": "Overview",
        "items": [
          {
            "label": "Home",
            "screen": "Home"
          },
          {
            "label": "Audit Log",
            "screen": "AuditLog"
          },
          {
            "label": "Reports",
            "screen": "Reports"
          }
        ]
      },
      {
        "group": "Books and records",
        "items": [
          {
            "label": "Finance",
            "screen": "Finance"
          },
          {
            "label": "Inventory",
            "screen": "Inventory"
          },
          {
            "label": "Payroll",
            "screen": "Payroll"
          },
          {
            "label": "Approvals History",
            "screen": "Approvals"
          },
          {
            "label": "Shifts and Day-end",
            "screen": "BillShift"
          }
        ]
      }
    ],
    "permissions": [
      "approvals:inbox:read",
      "audit:log:export",
      "audit:log:read",
      "billing:shift:read",
      "finance:*:read",
      "inventory:*:read",
      "myspace:*",
      "payroll:*:read"
    ]
  },
  "mrd": {
    "name": "Medical Records",
    "roles": "MRD Officer, Medical Coder",
    "home": "Home",
    "scope": "All records, no billing",
    "readOnly": false,
    "menu": [
      {
        "group": "Records",
        "items": [
          {
            "label": "Home",
            "screen": "Home"
          },
          {
            "label": "Medical Records",
            "screen": "Records"
          },
          {
            "label": "Patient Profile",
            "screen": "PatientProfile"
          },
          {
            "label": "Approvals",
            "screen": "Approvals"
          }
        ]
      },
      {
        "group": "Reports",
        "items": [
          {
            "label": "Reports",
            "screen": "Reports"
          }
        ]
      },
      {
        "group": "Personal",
        "items": [
          {
            "label": "My Space",
            "screen": "MySpace"
          }
        ]
      }
    ],
    "permissions": [
      "approvals:inbox:read",
      "mrd:*",
      "myspace:*",
      "patients:patient:read"
    ]
  },
  "kitchen": {
    "name": "Kitchen",
    "roles": "Dietitian, Kitchen Supervisor",
    "home": "Home",
    "scope": "Kitchen",
    "readOnly": false,
    "menu": [
      {
        "group": "Kitchen",
        "items": [
          {
            "label": "Home",
            "screen": "Home"
          },
          {
            "label": "Diet and Kitchen",
            "screen": "Diet"
          },
          {
            "label": "Kitchen Store",
            "screen": "Inventory"
          }
        ]
      },
      {
        "group": "Personal",
        "items": [
          {
            "label": "My Space",
            "screen": "MySpace"
          }
        ]
      }
    ],
    "permissions": [
      "diet:*",
      "inventory:*:read",
      "myspace:*"
    ]
  },
  "facility": {
    "name": "Facility",
    "roles": "Housekeeping Supervisor, Maintenance, Biomedical Engineer",
    "home": "Home",
    "scope": "Branch facilities",
    "readOnly": false,
    "menu": [
      {
        "group": "Facility",
        "items": [
          {
            "label": "Home",
            "screen": "Home"
          },
          {
            "label": "Housekeeping and Facility",
            "screen": "Facility"
          },
          {
            "label": "Bed Board",
            "screen": "Beds"
          },
          {
            "label": "Store Indents",
            "screen": "Inventory"
          },
          {
            "label": "Approvals",
            "screen": "Approvals"
          }
        ]
      },
      {
        "group": "Personal",
        "items": [
          {
            "label": "My Space",
            "screen": "MySpace"
          }
        ]
      }
    ],
    "permissions": [
      "approvals:inbox:read",
      "facility:*",
      "inventory:*:read",
      "ipd:bed:read",
      "myspace:*"
    ]
  },
  "quality": {
    "name": "Quality",
    "roles": "Quality Manager, Infection Control Nurse",
    "home": "Home",
    "scope": "Whole hospital, read-only clinical",
    "readOnly": false,
    "menu": [
      {
        "group": "Quality",
        "items": [
          {
            "label": "Home",
            "screen": "Home"
          },
          {
            "label": "Quality and Incidents",
            "screen": "Quality"
          },
          {
            "label": "Medical Records",
            "screen": "Records"
          },
          {
            "label": "Approvals",
            "screen": "Approvals"
          }
        ]
      },
      {
        "group": "Reports",
        "items": [
          {
            "label": "Reports",
            "screen": "Reports"
          }
        ]
      },
      {
        "group": "Services (read)",
        "items": [
          {
            "label": "Diet & Kitchen",
            "screen": "Diet"
          },
          {
            "label": "Facility",
            "screen": "Facility"
          },
          {
            "label": "CRM",
            "screen": "Crm"
          },
          {
            "label": "Microbiology (antibiogram)",
            "screen": "LabMicro"
          }
        ]
      },
      {
        "group": "Personal",
        "items": [
          {
            "label": "My Space",
            "screen": "MySpace"
          }
        ]
      }
    ],
    "permissions": [
      "approvals:inbox:read",
      "crm:*:read",
      "diet:*:read",
      "facility:*:read",
      "lab:micro:read",
      "mrd:*:read",
      "myspace:*",
      "quality:*"
    ]
  },
  "crm": {
    "name": "CRM and Call Centre",
    "roles": "CRM Executive, Call Centre",
    "home": "Home",
    "scope": "Patients, no clinical notes",
    "readOnly": false,
    "menu": [
      {
        "group": "Engagement",
        "items": [
          {
            "label": "Home",
            "screen": "Home"
          },
          {
            "label": "CRM",
            "screen": "Crm"
          },
          {
            "label": "Appointments",
            "screen": "Opd"
          },
          {
            "label": "Patients",
            "screen": "Patients"
          }
        ]
      },
      {
        "group": "Reports",
        "items": [
          {
            "label": "Reports",
            "screen": "Reports"
          }
        ]
      },
      {
        "group": "Personal",
        "items": [
          {
            "label": "My Space",
            "screen": "MySpace"
          }
        ]
      }
    ],
    "permissions": [
      "crm:*",
      "myspace:*",
      "opd:appointment:read",
      "patients:patient:read"
    ]
  },
  "employee": {
    "name": "Employee",
    "roles": "Every staff login",
    "home": "MySpace",
    "scope": "Own records",
    "readOnly": false,
    "menu": [
      {
        "group": "Personal",
        "items": [
          {
            "label": "My Space",
            "screen": "MySpace"
          }
        ]
      }
    ],
    "permissions": [
      "myspace:*"
    ]
  }
});
