// Generated by packages/shared/scripts/gen-catalog.js from docs/ui-design. Do not edit.
export const SCREENS = Object.freeze({
  "Main": {
    "title": "Overview",
    "route": null,
    "app": null,
    "module": null,
    "permissions": [],
    "role": "All",
    "apis": [],
    "phase": 0
  },
  "DesignSystem": {
    "title": "Design system",
    "route": null,
    "app": null,
    "module": null,
    "permissions": [],
    "role": "All",
    "apis": [],
    "phase": 0
  },
  "Login": {
    "title": "Login and 2FA",
    "route": "/login",
    "app": "web",
    "module": "CORE",
    "permissions": [],
    "role": "All users",
    "apis": [
      "POST /auth/login",
      "/auth/2fa/verify"
    ],
    "phase": 1
  },
  "Signup": {
    "title": "Pricing and signup",
    "route": "www/pricing",
    "app": "www",
    "module": null,
    "permissions": [],
    "role": "Prospect",
    "apis": [
      "GET /public/plans",
      "POST /public/signup"
    ],
    "phase": 0
  },
  "SetupWizard": {
    "title": "Setup wizard",
    "route": "/setup",
    "app": "web",
    "module": "CORE",
    "permissions": [
      "settings:*"
    ],
    "role": "Super Admin",
    "apis": [
      "PUT /branches",
      "/departments",
      "POST /masters/{type}/import"
    ],
    "phase": 1
  },
  "Console": {
    "title": "Platform console",
    "route": "console/",
    "app": "console",
    "module": null,
    "permissions": [
      "platform:*"
    ],
    "role": "Platform owner",
    "apis": [
      "GET /platform/tenants",
      "/platform/metrics"
    ],
    "phase": 0
  },
  "ConsoleTenant": {
    "title": "Tenant detail",
    "route": "console/tenants/:id",
    "app": "console",
    "module": null,
    "permissions": [
      "platform:tenant:*"
    ],
    "role": "Platform owner",
    "apis": [
      "GET /platform/tenants/{id}",
      "POST /platform/tenants/{id}/subscription"
    ],
    "phase": 0
  },
  "PanelMap": {
    "title": "Role panel map",
    "route": null,
    "app": null,
    "module": "CORE",
    "permissions": [],
    "role": "Everyone",
    "apis": [
      "GET /auth/me (roles, panels, menu)"
    ],
    "phase": 1
  },
  "Home": {
    "title": "Role home pages (25)",
    "route": "/home",
    "app": "web",
    "module": "CORE",
    "permissions": [],
    "role": "Each role",
    "apis": [
      "GET /me/home (queue, counts, alerts)"
    ],
    "phase": 1
  },
  "ClinicDesk": {
    "title": "Clinic desk (one-screen mode)",
    "route": "/clinic",
    "app": "web",
    "module": "OPD",
    "permissions": [
      "opd:*",
      "billing:bill:create"
    ],
    "role": "Clinic doctor and admin",
    "apis": [
      "GET /opd/queue",
      "PUT /opd/visits/{id}/consultation",
      "POST /billing/bills"
    ],
    "phase": 2
  },
  "Subscription": {
    "title": "Subscription",
    "route": "/settings/subscription",
    "app": "web",
    "module": "CORE",
    "permissions": [
      "settings:subscription:read"
    ],
    "role": "Super Admin",
    "apis": [
      "GET /subscription",
      "POST /subscription/preview"
    ],
    "phase": 1
  },
  "Dashboard": {
    "title": "Admin dashboard",
    "route": "/",
    "app": "web",
    "module": "CORE",
    "permissions": [
      "dashboard:admin:read"
    ],
    "role": "Admin",
    "apis": [
      "GET /dashboard/summary"
    ],
    "phase": 1
  },
  "Approvals": {
    "title": "Approvals",
    "route": "/approvals",
    "app": "web",
    "module": "CORE",
    "permissions": [
      "approvals:inbox:read"
    ],
    "role": "Checkers",
    "apis": [
      "GET /approvals",
      "POST /approvals/{id}/decision"
    ],
    "phase": 1
  },
  "Reports": {
    "title": "Reports",
    "route": "/reports",
    "app": "web",
    "module": null,
    "permissions": [],
    "role": "Managers",
    "apis": [
      "GET /reports/{code}",
      "POST /reports/{code}/export"
    ],
    "phase": 0
  },
  "AuditLog": {
    "title": "Audit log",
    "route": "/audit",
    "app": "web",
    "module": "CORE",
    "permissions": [
      "audit:log:read"
    ],
    "role": "Super Admin",
    "apis": [
      "GET /audit"
    ],
    "phase": 1
  },
  "Settings": {
    "title": "Hospital settings",
    "route": "/settings",
    "app": "web",
    "module": "CORE",
    "permissions": [
      "settings:hospital:*"
    ],
    "role": "Super Admin",
    "apis": [
      "GET/PUT /settings",
      "/branches",
      "/templates"
    ],
    "phase": 1
  },
  "Users": {
    "title": "Users",
    "route": "/settings/users",
    "app": "web",
    "module": "CORE",
    "permissions": [
      "settings:user:*"
    ],
    "role": "Admin",
    "apis": [
      "CRUD /users"
    ],
    "phase": 1
  },
  "Roles": {
    "title": "Roles and access",
    "route": "/settings/roles",
    "app": "web",
    "module": "CORE",
    "permissions": [
      "settings:role:*"
    ],
    "role": "Super Admin",
    "apis": [
      "CRUD /roles"
    ],
    "phase": 1
  },
  "Departments": {
    "title": "Departments and masters",
    "route": "/settings/masters",
    "app": "web",
    "module": "CORE",
    "permissions": [
      "settings:master:*"
    ],
    "role": "Admin",
    "apis": [
      "CRUD /departments",
      "/masters/{type}"
    ],
    "phase": 1
  },
  "Patients": {
    "title": "Patient registration",
    "route": "/patients/new",
    "app": "web",
    "module": "CORE",
    "permissions": [
      "patients:patient:create"
    ],
    "role": "Front Office",
    "apis": [
      "GET /patients?q=",
      "POST /patients"
    ],
    "phase": 1
  },
  "PatientProfile": {
    "title": "Patient profile",
    "route": "/patients/:id",
    "app": "web",
    "module": "CORE",
    "permissions": [
      "patients:patient:read"
    ],
    "role": "Clinical, front office",
    "apis": [
      "GET /patients/{id}",
      "/patients/{id}/timeline"
    ],
    "phase": 1
  },
  "FrontOffice": {
    "title": "Front office",
    "route": "/front-office",
    "app": "web",
    "module": "CORE",
    "permissions": [
      "frontoffice:*"
    ],
    "role": "Front Office",
    "apis": [
      "POST /front-office/tokens",
      "/passes"
    ],
    "phase": 1
  },
  "OpdCheckin": {
    "title": "OPD check-in",
    "route": "/opd/check-in",
    "app": "web",
    "module": "OPD",
    "permissions": [
      "opd:visit:create"
    ],
    "role": "Front Office",
    "apis": [
      "GET /opd/appointments?date=today",
      "POST /opd/appointments/{id}/check-in"
    ],
    "phase": 2
  },
  "OpdTriage": {
    "title": "OPD triage",
    "route": "/opd/triage",
    "app": "web",
    "module": "OPD",
    "permissions": [
      "opd:vitals:create"
    ],
    "role": "Staff Nurse",
    "apis": [
      "GET /opd/queue?stage=triage",
      "POST /opd/visits/{id}/vitals"
    ],
    "phase": 2
  },
  "OpdConfig": {
    "title": "OPD settings",
    "route": "/settings/opd",
    "app": "web",
    "module": "OPD",
    "permissions": [
      "opd:schedule:*",
      "opd:settings:*"
    ],
    "role": "Hospital Admin",
    "apis": [
      "CRUD /opd/schedules",
      "PUT /opd/settings"
    ],
    "phase": 2
  },
  "OpdAnalytics": {
    "title": "OPD analytics",
    "route": "/opd/analytics",
    "app": "web",
    "module": "OPD",
    "permissions": [
      "reports:opd:read"
    ],
    "role": "Management",
    "apis": [
      "GET /reports/opd-wait-times",
      "/reports/opd-doctor-performance"
    ],
    "phase": 2
  },
  "PortalBooking": {
    "title": "Patient mobile booking",
    "route": "/my/book",
    "app": "portal",
    "module": "CORE",
    "permissions": [],
    "role": "Patient",
    "apis": [
      "GET /public/doctors",
      "POST /portal/appointments",
      "POST /portal/payments"
    ],
    "phase": 1
  },
  "Opd": {
    "title": "OPD appointments",
    "route": "/opd",
    "app": "web",
    "module": "OPD",
    "permissions": [
      "opd:appointment:*"
    ],
    "role": "Front Office",
    "apis": [
      "GET /opd/slots",
      "POST /opd/appointments"
    ],
    "phase": 2
  },
  "Consult": {
    "title": "Consultation",
    "route": "/opd/visits/:id",
    "app": "web",
    "module": "OPD",
    "permissions": [
      "opd:consultation:write"
    ],
    "role": "Doctor",
    "apis": [
      "PUT /opd/visits/{id}/consultation"
    ],
    "phase": 2
  },
  "IpdRounds": {
    "title": "In-patient rounds",
    "route": "/ipd/rounds",
    "app": "web",
    "module": "IPD",
    "permissions": [
      "ipd:note:write",
      "orders:*"
    ],
    "role": "Doctor",
    "apis": [
      "GET /ipd/admissions?doctor=me",
      "POST /orders"
    ],
    "phase": 3
  },
  "Admission": {
    "title": "Admission",
    "route": "/ipd/admit",
    "app": "web",
    "module": "IPD",
    "permissions": [
      "ipd:admission:create"
    ],
    "role": "Admission Desk",
    "apis": [
      "POST /ipd/admissions"
    ],
    "phase": 3
  },
  "Beds": {
    "title": "Bed board",
    "route": "/ipd/beds",
    "app": "web",
    "module": "IPD",
    "permissions": [
      "ipd:bed:read"
    ],
    "role": "Admission Desk",
    "apis": [
      "GET /ipd/beds + socket bed:update"
    ],
    "phase": 3
  },
  "Discharge": {
    "title": "Discharge desk",
    "route": "/ipd/discharge",
    "app": "web",
    "module": "IPD",
    "permissions": [
      "ipd:discharge:*"
    ],
    "role": "Doctor, billing",
    "apis": [
      "PUT /ipd/admissions/{id}/discharge-summary"
    ],
    "phase": 3
  },
  "IpdBedRequests": {
    "title": "Bed requests and transfers",
    "route": "/ipd/bed-requests",
    "app": "web",
    "module": "IPD",
    "permissions": [
      "ipd:bed:allocate"
    ],
    "role": "Ward In-charge, Admission Desk",
    "apis": [
      "GET /ipd/bed-requests",
      "POST /ipd/bed-requests/{id}/reserve",
      "POST /ipd/transfers"
    ],
    "phase": 3
  },
  "IpdTpa": {
    "title": "Insurance and TPA desk",
    "route": "/ipd/insurance",
    "app": "web",
    "module": "IPD",
    "permissions": [
      "ipd:preauth:*"
    ],
    "role": "Billing Manager (TPA desk)",
    "apis": [
      "GET /ipd/preauths?open=true",
      "POST /ipd/preauths/{id}/enhancements",
      "POST /ipd/claims"
    ],
    "phase": 3
  },
  "IpdBill": {
    "title": "In-patient bill",
    "route": "/ipd/bills",
    "app": "web",
    "module": "IPD",
    "permissions": [
      "billing:ip:*"
    ],
    "role": "Cashier",
    "apis": [
      "GET /ipd/admissions/{id}/bill",
      "POST /ipd/admissions/{id}/final-bill"
    ],
    "phase": 3
  },
  "IpdConfig": {
    "title": "IPD settings",
    "route": "/settings/ipd",
    "app": "web",
    "module": "IPD",
    "permissions": [
      "ipd:settings:*"
    ],
    "role": "Hospital Admin",
    "apis": [
      "CRUD /ipd/wards",
      "/ipd/beds",
      "/ipd/packages",
      "PUT /ipd/settings"
    ],
    "phase": 3
  },
  "IpdAnalytics": {
    "title": "IPD analytics",
    "route": "/ipd/analytics",
    "app": "web",
    "module": "IPD",
    "permissions": [
      "reports:ipd:read"
    ],
    "role": "Management",
    "apis": [
      "GET /reports/ipd-census",
      "/reports/ipd-indicators"
    ],
    "phase": 3
  },
  "PortalStay": {
    "title": "Attendant mobile screens",
    "route": "/my/stay",
    "app": "portal",
    "module": "CORE",
    "permissions": [],
    "role": "Patient, attendant",
    "apis": [
      "GET /portal/admissions/current",
      "/portal/admissions/{id}/bill",
      "POST /portal/payments"
    ],
    "phase": 1
  },
  "BillShift": {
    "title": "Cashier shift and day-end",
    "route": "/billing/shift",
    "app": "web",
    "module": "CORE",
    "permissions": [
      "billing:shift:*"
    ],
    "role": "Cashier, Billing Manager",
    "apis": [
      "POST /billing/shifts",
      "POST /billing/shifts/{id}/close",
      "POST /billing/days/{date}/lock"
    ],
    "phase": 1
  },
  "BillCorporate": {
    "title": "Corporate and credit",
    "route": "/billing/corporates",
    "app": "web",
    "module": "CORE",
    "permissions": [
      "billing:corporate:*"
    ],
    "role": "Billing Manager",
    "apis": [
      "GET /billing/corporates",
      "POST /billing/corporate-invoices",
      "POST /billing/einvoice/{id}"
    ],
    "phase": 1
  },
  "BillConfig": {
    "title": "Billing settings",
    "route": "/settings/billing",
    "app": "web",
    "module": "CORE",
    "permissions": [
      "billing:settings:*"
    ],
    "role": "Hospital Admin",
    "apis": [
      "PUT /billing/settings",
      "CRUD /billing/series",
      "/billing/price-lists"
    ],
    "phase": 1
  },
  "BillAnalytics": {
    "title": "Billing analytics",
    "route": "/billing/analytics",
    "app": "web",
    "module": "CORE",
    "permissions": [
      "reports:billing:read"
    ],
    "role": "Management, Accounts",
    "apis": [
      "GET /reports/revenue",
      "/reports/receivables-ageing",
      "/reports/leakage"
    ],
    "phase": 1
  },
  "PortalPay": {
    "title": "Patient payments on the phone",
    "route": "/my/bills",
    "app": "portal",
    "module": "CORE",
    "permissions": [],
    "role": "Patient",
    "apis": [
      "GET /portal/bills",
      "POST /portal/payments",
      "GET /portal/receipts"
    ],
    "phase": 1
  },
  "LabSample": {
    "title": "Sample collection and receipt",
    "route": "/lab/samples",
    "app": "web",
    "module": "LAB",
    "permissions": [
      "lab:sample:*"
    ],
    "role": "Lab reception, nurse",
    "apis": [
      "GET /lab/samples?status=in-transit",
      "POST /lab/samples/{id}/accept",
      "POST /lab/samples/{id}/reject"
    ],
    "phase": 4
  },
  "LabQC": {
    "title": "Quality control",
    "route": "/lab/qc",
    "app": "web",
    "module": "LAB",
    "permissions": [
      "lab:qc:*"
    ],
    "role": "Lab technician, pathologist",
    "apis": [
      "POST /lab/qc/runs",
      "GET /lab/qc/levey-jennings?control="
    ],
    "phase": 4
  },
  "LabMicro": {
    "title": "Microbiology",
    "route": "/lab/micro",
    "app": "web",
    "module": "LAB",
    "permissions": [
      "lab:micro:*"
    ],
    "role": "Microbiologist",
    "apis": [
      "GET /lab/cultures",
      "POST /lab/cultures/{id}/readings",
      "POST /lab/cultures/{id}/sensitivity"
    ],
    "phase": 4
  },
  "LabHisto": {
    "title": "Histopathology",
    "route": "/lab/histo",
    "app": "web",
    "module": "LAB",
    "permissions": [
      "lab:histo:*"
    ],
    "role": "Pathologist",
    "apis": [
      "GET /lab/histo/cases",
      "PUT /lab/histo/cases/{id}",
      "POST /lab/histo/cases/{id}/release"
    ],
    "phase": 4
  },
  "LabConfig": {
    "title": "Lab settings",
    "route": "/settings/lab",
    "app": "web",
    "module": "LAB",
    "permissions": [
      "lab:settings:*"
    ],
    "role": "Lab in-charge",
    "apis": [
      "CRUD /lab/tests",
      "/lab/ranges",
      "/lab/critical-values",
      "/lab/partners"
    ],
    "phase": 4
  },
  "LabAnalytics": {
    "title": "Lab analytics",
    "route": "/lab/analytics",
    "app": "web",
    "module": "LAB",
    "permissions": [
      "reports:lab:read"
    ],
    "role": "Management, lab in-charge",
    "apis": [
      "GET /reports/lab-tat",
      "/reports/lab-indicators"
    ],
    "phase": 4
  },
  "PhleboPhone": {
    "title": "Phlebotomist phone screens",
    "route": "app /visits",
    "app": "web",
    "module": "LAB",
    "permissions": [
      "lab:homevisit:*"
    ],
    "role": "Phlebotomist",
    "apis": [
      "GET /lab/home-visits?mine=today",
      "POST /lab/home-visits/{id}/collect"
    ],
    "phase": 4
  },
  "Nursing": {
    "title": "Nursing station",
    "route": "/nursing/:wardId",
    "app": "web",
    "module": "NUR",
    "permissions": [
      "nursing:*"
    ],
    "role": "Staff Nurse",
    "apis": [
      "GET /nursing/wards/{id}/census",
      "POST /nursing/mar/{doseId}/administer"
    ],
    "phase": 3
  },
  "Roster": {
    "title": "Shift roster",
    "route": "/hr/rosters",
    "app": "web",
    "module": "HRM",
    "permissions": [
      "hr:roster:write"
    ],
    "role": "Ward In-charge",
    "apis": [
      "GET/PUT /hr/rosters"
    ],
    "phase": 5
  },
  "Lab": {
    "title": "Laboratory",
    "route": "/lab",
    "app": "web",
    "module": "LAB",
    "permissions": [
      "lab:*"
    ],
    "role": "Lab, pathologist",
    "apis": [
      "GET /lab/worklists",
      "PUT /lab/tests/{id}/results"
    ],
    "phase": 4
  },
  "Radiology": {
    "title": "Radiology",
    "route": "/radiology",
    "app": "web",
    "module": "RAD",
    "permissions": [
      "rad:*"
    ],
    "role": "Radiologist",
    "apis": [
      "PUT /rad/studies/{id}/report",
      "POST /sign"
    ],
    "phase": 4
  },
  "Pharmacy": {
    "title": "Pharmacy",
    "route": "/pharmacy",
    "app": "web",
    "module": "PHR",
    "permissions": [
      "pharmacy:*"
    ],
    "role": "Pharmacist",
    "apis": [
      "GET /pharmacy/rx-queue",
      "POST /pharmacy/sales"
    ],
    "phase": 4
  },
  "Billing": {
    "title": "Billing counter",
    "route": "/billing",
    "app": "web",
    "module": "CORE",
    "permissions": [
      "billing:*"
    ],
    "role": "Cashier",
    "apis": [
      "POST /billing/bills",
      "/bills/{id}/payments"
    ],
    "phase": 1
  },
  "Finance": {
    "title": "Finance",
    "route": "/finance",
    "app": "web",
    "module": "FIN",
    "permissions": [
      "finance:*"
    ],
    "role": "Accountant",
    "apis": [
      "GET /finance/trial-balance",
      "POST /finance/vouchers"
    ],
    "phase": 5
  },
  "Inventory": {
    "title": "Inventory",
    "route": "/inventory",
    "app": "web",
    "module": "INV",
    "permissions": [
      "inventory:*"
    ],
    "role": "Store Keeper",
    "apis": [
      "GET /inventory/stock",
      "POST /inventory/purchase-orders"
    ],
    "phase": 4
  },
  "Hr": {
    "title": "HR",
    "route": "/hr",
    "app": "web",
    "module": "HRM",
    "permissions": [
      "hr:*"
    ],
    "role": "HR Manager",
    "apis": [
      "CRUD /hr/employees",
      "POST /hr/leave-requests/{id}/decision"
    ],
    "phase": 5
  },
  "Payroll": {
    "title": "Payroll",
    "route": "/payroll",
    "app": "web",
    "module": "PAY",
    "permissions": [
      "payroll:*"
    ],
    "role": "Payroll Officer",
    "apis": [
      "POST /payroll/runs",
      "GET /payroll/runs/{id}"
    ],
    "phase": 5
  },
  "Records": {
    "title": "Medical records",
    "route": "/records",
    "app": "web",
    "module": "MRD",
    "permissions": [
      "mrd:*"
    ],
    "role": "MRD Officer",
    "apis": [
      "GET /mrd/deficiencies",
      "POST /mrd/births",
      "/mrd/deaths"
    ],
    "phase": 6
  },
  "Diet": {
    "title": "Diet and kitchen",
    "route": "/diet",
    "app": "web",
    "module": "DIET",
    "permissions": [
      "diet:*"
    ],
    "role": "Dietitian",
    "apis": [
      "GET /diet/production",
      "PUT /diet/orders/{id}"
    ],
    "phase": 6
  },
  "Facility": {
    "title": "Facility",
    "route": "/facility",
    "app": "web",
    "module": "FAC",
    "permissions": [
      "facility:*"
    ],
    "role": "Supervisor",
    "apis": [
      "GET /facility/hk-tasks",
      "POST /facility/tickets"
    ],
    "phase": 6
  },
  "Quality": {
    "title": "Quality",
    "route": "/quality",
    "app": "web",
    "module": "QLT",
    "permissions": [
      "quality:*"
    ],
    "role": "Quality Manager",
    "apis": [
      "POST /quality/incidents",
      "GET /quality/indicators"
    ],
    "phase": 6
  },
  "Crm": {
    "title": "Patient CRM",
    "route": "/crm",
    "app": "web",
    "module": "CRM",
    "permissions": [
      "crm:*"
    ],
    "role": "CRM Executive",
    "apis": [
      "CRUD /crm/leads",
      "POST /crm/campaigns"
    ],
    "phase": 6
  },
  "MySpace": {
    "title": "My space",
    "route": "/me",
    "app": "web",
    "module": "HRM",
    "permissions": [],
    "role": "Every employee",
    "apis": [
      "GET /payroll/payslips/me",
      "POST /hr/leave-requests"
    ],
    "phase": 5
  },
  "QueueTV": {
    "title": "Queue TV",
    "route": "/display/queue",
    "app": "web",
    "module": "OPD",
    "permissions": [],
    "role": "Display screen",
    "apis": [
      "socket queue:update"
    ],
    "phase": 2
  },
  "Portal": {
    "title": "Patient portal",
    "route": "/my (patient)",
    "app": "portal",
    "module": "CORE",
    "permissions": [],
    "role": "Patient",
    "apis": [
      "POST /portal/auth/otp",
      "GET /portal/me/documents"
    ],
    "phase": 1
  },
  "PrintBill": {
    "title": "Print templates",
    "route": "server PDF",
    "app": "web",
    "module": "CORE",
    "permissions": [
      "billing:bill:print"
    ],
    "role": "-",
    "apis": [
      "GET /billing/bills/{id}/pdf"
    ],
    "phase": 1
  },
  "States": {
    "title": "Screen states",
    "route": null,
    "app": null,
    "module": null,
    "permissions": [],
    "role": "All",
    "apis": [
      "Error format in API docs"
    ],
    "phase": 0
  }
});
